<?php
       foreach ($this->payments as $row) {
           echo "<span class='finisn_transaction' payment_id='". $row->id. "'> finish transaction ".$row->payment_id."  status :   ".$row->payment_status ."</span>";
           echo "<br>";
     }
?>
<script type="text/javascript">

    $(function(){

        $('.finisn_transaction').bind('click',function(){
            finish_payment(this);

        });
    });
    function finish_payment(element){
        var payment_id = $(element).attr("payment_id");
        $.ajax({
            type: "POST",
            url:  "payment/finishpayment",
            data:{payment_id : payment_id}
        })
            .done(function( data ) {
                $.ajax({
                    type: "GET",
                    url: "payment/getfinishedpayments"

                })
                    .done(function( data ) {
                        $("#finished_payments").html(data);
                    });
            });

    }
</script>