<?php foreach ($this->data as $data_key => $data_value) {
    echo "<h1>Project name: ".$data_key."</h1>";
    //var_dump($data_value);
    foreach ($data_value as $report_key => $report_value) {


        foreach ($report_value as $row_key => $row_value) {
            echo "<p>Task: ".$row_key.". Estimation: ".$row_value["estimate"]." Reported <b style='font-size: 15px;'>".$row_value['hours']."</b> by: ".$row_value["user_name"]."</p>";
        }

   //     var_dump($report_value);
    }
}
