<?php foreach ($this->members as $member) {
    echo "<span>" . $member["first_name"] . " " . $member["second_name"] . "  <input type='button' value='-' class='remove_user_from_project action_btn'  user_id=".$member['user_id']." project_id=".$member['project_id']."></span>";
} ?>
<script type="text/javascript">
    $(function () {
        $(".remove_user_from_project").on("click", function () {
            var user_id = $(this).attr("user_id");
            var project_id = $(this).attr("project_id");
            $.ajax({
                type: "post",
                url: "projects/deleteUserFromProject",
                async: true,
                data: {"project_id": project_id, 'user_id': user_id }
        }).
            done(function (data) {
                edit_project_members();
            });
        });
    });
</script>
