<?php
$this->translator = $GLOBALS["HELPERS"]["TRANSLATOR"];
?>
<?php foreach ($this->data as $data_key => $data_value) {
    echo "<h1>";
    echo $this->translator["Project_Name"]; 
    echo  $data_key."</h1>";
        foreach ($data_value as $row_key => $row_value) {
            echo "<p>";
            echo $this->translator["Task"]; 
            echo $row_key;
            echo $this->translator["Estimation"]; 
            echo $row_value["estimate"];
            echo $this->translator["Reported"]; 
            echo "<b style='font-size: 15px;'>".$row_value['hours']."</b> by: ".$row_value["user_name"]."</p>";
        }
}
