<?php
$this->translator = $GLOBALS["HELPERS"]["TRANSLATOR"];
?>
<div id="projects_div">
	<div class="col col-3">
		<ul class="projects_list">
<?php
if (isset($projects)) {
    foreach ($projects as $project) {
        echo '<li class="open_project" projectId="' . $project["id"] . '">' . $project["project_name"] . '<div class="open_project" projectId="' . $project["id"] . '">';
        echo $this->translator["open"]; 
        echo '</span><span class="archive_project" projectId="' . $project["id"] . '">';
        echo $this->translator["archive"]; 
        echo "</div></li>";
    }
}
?>
</ul>
	</div>
</div>
<div class="projects_archive">
	<span id="load_projects_archive">   <?php   echo $this->translator["load_projects_archive"]; ?></span>
	<div id="projects_archive_block"></div>

</div>
<div class="col col-12">
	<div id="create_project_button"> + <?php   echo $this->translator["create_project"]; ?> </div>


<div id="project_popup" style="display: block;">
	<div style="width: 100%;">
		<input type="text" name="project_name" placeholder="project name"
			id="project_name"> </br>
		<textarea name="project_description" placeholder="project description"
			id="project_description"></textarea>
		</br> <input type="button" name="project_save" class="action_btn"
			value="<?php   echo $this->translator["save_project"]; ?>" id="create_project">
	</div>
	<div style="display: block;" id="project_members"></div>
</div>
	<div id="project_members_list"></div>

</div>


<script type="text/javascript">
    $(function(){
        $("#load_projects_archive").on("click" , function (){
            $(function () {
                $.ajax({
                    type: "GET",
                    url: "projects/loadProjectsArchive"
                })
                    .done(function (data) {
                        data = JSON.parse(data);
                        for (const [key, value] of Object.entries(data)) {
                                $("#projects_archive_block").append('<div>'+value.project_name+":"
                                    + value.project_description+'<span class="delete_project"  project_id="'+ value.id +'">delete</span>' +
                                    '<span class="restore_project"  project_id="'+ value.id +'">restore</span></div>');
                        }
                        $(".restore_project").on("click",function (){
                            $.ajax({
                                type: "POST",
                                url: "projects/updateProject",
                                async:false,
                                data : {"id":$(this).attr("project_id"),"is_archive" : 0}
                            })
                                .done(function( data ) {
                                    $.ajax({
                                        type: "GET",
                                        url: "projects/index"
                                    })
                                        .done(function (data) {
                                            $("#tasks_transaction").html(data);
                                        });
                                });
                        });

                        $(".delete_project").on("click",function (){
                            $.ajax({
                                type: "POST",
                                url: "projects/deleteProject",
                                async:false,
                                data : {"id":$(this).attr("project_id")}
                            })
                                .done(function( data ) {
                                    $.ajax({
                                        type: "GET",
                                        url: "projects/index"
                                    })
                                        .done(function (data) {
                                            $("#tasks_transaction").html(data);
                                        });
                                });
                        })
                    });

            });
        });


        $("#create_project_button").on("click" , function(){
            $("#project_popup").show();
            refresh_project_members_list();
        });
    });

        $(".open_project").on("click",function(){
            var project_id = $(this).attr("projectId");
            $.ajax({
                type: "POST",
                url: "boards/index",
                async:false,
                data : {"project_id":project_id}
            })
                .done(function( data ) {

                            $("#tasks_transaction").html(data);
                        });
                });




        $(".archive_project").on("click",function(){
            var project_id = $(this).attr("projectId");
            $.ajax({
                type: "POST",
                url: "projects/updateProject",
                async:false,
                data : {"id":project_id,"is_archive" : 1}
            })
                .done(function( data ) {
                    $.ajax({
                        type: "GET",
                        url: "projects/index"
                    })
                        .done(function (data) {
                            $("#tasks_transaction").html(data);
                        });
                });
         });


  $('.projects_list').sortable({

      update: function( event, ui ) {
          var projects_list = [];
          $(event.target).find("li").each(function( index, e ) {
              projects_list.push({"sort_order":index,"id":$(e).attr("projectId")});
          });
          console.info(projects_list);
          $.ajax({
              type: "POST",
              url: "projects/updateProjectsInBoard",
              data: {"projects_list":projects_list}
          })
      }
  });
  function refresh_project_members_list(){
        $.ajax({
            type: "GET",
            url: "friends/getfriendForProjectMemberlist",
            async:false
        })
            .done(function( data ) {
                $("#project_members_list").html(data);
            });
    }


    $("#project_popup #create_project").on("click",function(){
        var project_name =  $("#project_name").val();
        var members_list = [];
        var task_members_lsit =  $("#project_members div").each(function( index, e ) {
            members_list.push($(e).attr("userId"));
        });
        var project_description =  $("#project_description").val();
        var data = {"project_name":project_name,"members_list":members_list,"project_description":project_description};
            $.ajax({
                type: "POST",
                url: "projects/createProject",
                dataType: "json",
                data: data
            }).done(function()  {
                $.ajax({
                    type: "GET",
                    url: "projects/index"
                })
                    .done(function( data ) {
                        $("#tasks_transaction").html(data);
                    });
            }).fail(function()  {
            alert("Sorry. Server unavailable. ");
        });
    });
</script>
