<input type="hidden" class='parent_directory_network' style='cursor:pointer;' dir_key=<?php echo $current_directory?> />
<?php
if(isset($dirs) and count($dirs)) {
    foreach ($dirs as $dir_key => $dir_value) {
        echo "<div style='margin-left: 20px;'><img src='assets/images/icons/folder.png' width='50px' height='50px'/><span style='cursor:pointer;margin-top: -8px;margin-left: 5px;' dir_key=" . $dir_value['id'] . " class='network_directory'>" . $dir_value['path'] . "</span></div>";

    }
}
if(isset($filesInDir) and count($filesInDir)) {
    foreach ($filesInDir as $file) {
        if(isset($user_id) and (isset($file)))
        echo "<div class='file_wraper ' file=" . $file['id'] . ">";
        echo "<div class='file_block_wrapper hard-drive-directory-inner'>";
            echo "<img src='assets/images/icons/file.png' width='50px' height='50px' file=" . $file['id'] . " >";
            echo "<p class='file_block'> ".$file['file_title'] ."</p>";
            echo "<div class='network_actions'>";
            echo "<a href='/network/downloadFile/" . $user_id . "/" . $file['id'] . "' class='download_file' fileId=" . $file['id'] . ">
                      <img class='directory_action' src='assets/images/icons/download.png'>
                  </a>";
            echo "<a href='#' class='copy_file_from_network' file_id='" . $file['id'] . "'>
                      <img class='directory_action' src='assets/images/icons/move.png'>
                </a>";
        echo "</div>";
        echo "</div>";
        echo "</div>";
    }
}
?>
<script type="text/javascript">
    function copy_file_from_network(){
        $("#window_drive").css("display","block");
        show_directory(0);
        var file_id = $(this).attr("file_id");
        $("#paste").addClass("pastpaste_file_to_directory");
        window.need_to_paste_file = true;
        window.need_to_paste_file_id = file_id;
    }


    function get_network_directory() {
        $.ajax({
                type: "POST",
                url: "network/getnetworkfolder",
                data: {dir_key: $(this).attr("dir_key"), user_id:<?php echo $user_id; ?>}
            }
        )
            .done(function (data) {
                $("#network_frame").html(data);


            });
    }

    function get_network_parent_directory () {

        $.ajax({
                type: "POST",
                url: "network/getnetworkparentfolder",
                data: {dir_key: <?php echo $current_directory; ?>, user_id:<?php echo $user_id; ?>}
            }
        )
            .done(function (data) {
                $("#network_frame").html(data);
                let dir = $(".parent_directory_network").attr("dir_key");
                $("#get_parent_directory").attr("dir_key",dir);
            });

    }

$(function(){
    $(".network_directory").bind("click",get_network_directory);
    $("#get_parent_directory").bind("click",get_network_parent_directory);
    $(".copy_file_from_network").bind("click",copy_file_from_network);
    let dir = $(".parent_directory_network").attr("dir_key");
    $("#get_parent_directory").attr("dir_key",dir);

});

</script>
