<h3 class='parent_directory_network' style='cursor:pointer;' dir_key=<?php echo $current_directory?>><img  style='cursor:pointer;'src='assets/images/icons/go-back-icon.png' width='50px' height='50px'/></h3>

<?php
foreach($dirs as  $dir_key => $dir_value) {
    echo "<div style='margin-left: 20px;'><img src='assets/images/icons/folder.png' width='50px' height='50px'/><span style='cursor:pointer;margin-top: -8px;margin-left: 5px;' dir_key=".$dir_value['id']." class='network_directory'>".$dir_value['path']."</span></div>" ;

}
if($filesInDir) {
    foreach($filesInDir as  $file) {
        echo "<span style='display:inline;' class='file_delete_string' file=".$file['id'].">".$file['file_title']."     ".$file['type']."<a href='/network/downloadFile/".$user_id."/".$file['id']."' class='download_file' fileId=".$file['id'].">download file</a></span></br>";
    }
}
?>
<script type="text/javascript">

$(function(){
    $(".network_directory").bind("click",get_network_directory);
    $(".parent_directory_network").bind("click",get_network_parent_directory);

});
    function get_network_directory() {
        $.ajax({
                type: "POST",
                url: "network/getnetworkfolder",
                data: {dir_key: $(this).attr("dir_key"), user_id:<?php echo $user_id; ?>}
            }
        )
            .done(function (data) {
                $("#network").html(data);


            });
    }

    function get_network_parent_directory () {

        $.ajax({
                type: "POST",
                url: "network/getnetworkparentfolder",
                data: {dir_key: <?php echo $current_directory; ?>, user_id:<?php echo $user_id; ?>}
            }
        )
            .done(function (data) {
                $("#network").html(data);


            });

    }
</script>