<h3 class='parent_directory_network' style='cursor:pointer;position: absolute;top: 25px;left: 300px;' dir_key=<?php echo $current_directory?>><img  style='cursor:pointer;'src='assets/images/icons/go-back-icon.png' width='50px' height='50px'/></h3>
<?php
foreach($dirs as  $dir_key => $dir_value) {
    echo "<div style='margin-left: 20px;'><img src='assets/images/icons/folder.png' width='50px' height='50px'/><span style='cursor:pointer;margin-top: -8px;margin-left: 5px;' user_id=".$dir_value['user_id']." dir_key=".$dir_value['path_id']." class='network_directory'>".$dir_value['path']."</span></div>" ;

}
?>

<script type="text/javascript">

    $(function(){
        $(".network_directory").bind("click",get_network_access);
        //$(".parent_directory_network").bind("click",get_network_parent_directory);
    });

    function get_network_access(){
        $.ajax({
            type: "POST",
            url: "network/getnetworkdirectory",
            data: {user_id:$(this).attr("user_id"), dir_key : $(this).attr("dir_key")}
        })
            .done(function(data) {
                $("#network").html(data);
               // console.info(data);
            });

    }
    // function get_network_parent_directory () {
    //
    //     $.ajax({
    //             type: "POST",
    //             url: "network/getnetworkparentfolder",
    //             data: {dir_key: "network_list"}
    //         }
    //     )
    //         .done(function (data) {
    //             $("#network").html(data);
    //
    //         });
    //
    // }
</script>