<?php
if (isset($friends) and $friends)
    foreach ($friends as $friend) {
        if(isset($friend['first_name']) or isset($friend['second_name'])) {
        echo "<div class='network_point' style='cursor:pointer;' user_id=" . $friend['user_id'] . ">";
//         echo "<div class='network_avatar'>";
//         echo "<img src='" . $friend['avatar'] . "'>";
//         echo "</div>";
        ?>
        <div class="c-post__author-detais">
            <div class="c-post__author-name">
                <?php echo $friend['first_name']; ?> <?php echo $friend['second_name']; ?>
            </div>
            <div class="c-post__author-job">
               <button class='action_btn'>Open</button>
            </div>
        </div>
        <?php echo "</div>";
        }
    }
?>
<script type="text/javascript">


    $(function () {
        $(".network_point").bind("click", function () {
            var user_id = $(this).attr('user_id');
            get_network_point(user_id);

        })


    });

    function get_network_point(user_id) {
        $.ajax({
            type: "POST",
            url: "network/getnetworkpoint",
            data: {user_id: user_id}
        })
            .done(function (data) {
                $("#network_frame").html(data);
            });

    }
</script>
