
<script type="text/javascript">

    $(function(){

        $.ajax({
            type: "POST",
            url: "network/getnetworkfolder",
            data: {dir_key:<?php echo $dir_key; ?>,user_id:<?php echo $user_id; ?>}
            }
        )
            .done(function(data) {
                $("#network_frame").html(data);
                $(".network_directory").bind("click",get_network_directory);
                $(".parent_directory_network").bind("click",get_network_parent_directory);
            });
    });
</script>
