<div id="directory_password" style="display:hidden;" title="Enter Passowrd">

    <input type="password" dir_key="<?php echo $dir_key;?>" id="network_password" directory_owner=<?php echo $user_id;?>>
    <input type="button" value="ok" id="sudmit_direcotry_password">
</div>
<script type="text/javascript">

    $(function(){
        $("#sudmit_direcotry_password").bind("click",function(){

            $.ajax({
                type: "POST",
                url: "network/networkdirectorylogin",
                data: {password:$("#network_password").val(), dir_key : $("#network_password").attr("dir_key"),user_id : $("#network_password").attr("directory_owner")}
            })
                .done(function(data) {
                    $("#network").html(data);
                    // console.info(data);
                });
        });
        $("#directory_password").dialog();
    });
</script>