<div id="fb-root"></div>
 <script src="//connect.facebook.net/en_US/all.js"></script>
<script type="text/javascript">
    $(function(){
        FB.init({
            appId  : '1421006771545109',
            status : true, // check login status
            cookie : true, // enable cookies to allow the server to access the session
            xfbml  : true, // parse XFBML
            channelUrl : '52.11.234.214/facebook/login', // channel.html file
            oauth  : true // enable OAuth 2.0
        });
        FB.login(function(response) {
            console.info(response);
            // handle the response
        }, {scope:
        'public_profile,user_friends,email,user_about_me,user_actions.books,user_actions.fitness,user_actions.music' +
        ',user_actions.news,user_actions.video,user_activities,user_birthday,user_education_history,user_events,user_groups,'+
        ',user_games_activity,user_hometown,user_interests,user_likes,user_location,user_photos,user_posts,user_relationships,user_relationship_details,' +
        'user_religion_politics,user_status,user_tagged_places,user_videos,user_website,user_work_history,read_friendlists,read_insights,read_mailbox,' +
        'read_page_mailboxes,read_stream,manage_notifications,publish_actions'});

    });

</script>

