<?php
if (isset($frames) and count($frames)) {
    foreach ($frames as $frame) {
        echo "<div class='frame_list_block'>";
        echo "<img src='/" . $frame['image'] . "'/>";
        echo "<p class='frame_block'>" . $frame['name'] . "<button frame_url='" . $frame['url'] . "' class='open_frame action_btn'>open</button><button frame_id='" . $frame['id'] . "' class='delete_frame action_btn'>delete</button></p>";
        echo "</div>";
    }
}
?>
<script type="text/javascript">
    $(function () {
        $(".delete_frame").on("click", function () {
            const frame_id = $(this).attr("frame_id");
            $.post("frames/deleteFrame", {frame_id: frame_id}).done(function (data) {
                load_frames();
            });
        });
        $(".open_frame").on("click", function () {
            const url = $(this).attr("frame_url");
            const markup = '<iframe src="' + url + '" sandbox="allow-top-navigation allow-scripts allow-forms" data-tf-redirect-target=”_self” width="500" height="500" align="left" id="main_frame"></iframe>';
            $(".frame_container_output").html(markup);
            $(".frame_container_output").css("display", "block");
            $(".frame_container_output").css("width", "50%");
            $(".frame_container_output").css("height", "50%");
        })
    });
</script>
