<!-- TODO: Don't delete! Temporarily stopped here.
<div class="c-chat-card">
    <div class="c-chat-card__inner">
        <div class="c-chat-card__image-wrap">
            <img src="https://www.fillmurray.com/360/360" alt="" class="c-chat-card__image">
        </div>

        <div class="c-chat-card__main">
            <div class="c-chat-card__title">
                Some channel name
            </div>

            <div class="c-chat-card__author">
                {{channel_author}}
            </div>
        </div>

        <div class="c-chat-card__controls">
            <button class="c-chat-card__enter-button" type="button">
                <svg class="icon-nw icon-nw-open-in-new-black-24" viewBox="0 0 24 24">
                    <path d="M0 0h24v24H0V0z" fill="none"/>
                    <path d="M19 19H5V5h7V3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z"/>
                </svg>

                Open
            </button>
        </div>
    </div>
</div>
-->

<?php foreach ($chanels as $chanel) : ?>
    <div class="c-chat-card">
        <div class="c-chat-card__inner">
            <div class="c-chat-card__image-wrap">
                <img src="https://www.fillmurray.com/360/360" alt="" class="c-chat-card__image">
            </div>

            <div class="c-chat-card__main">
                <div class="c-chat-card__title">
                    <?php echo $this->escapeHtml($chanel->chanel_name); ?>
                </div>

                <div class="c-chat-card__author">
                    {{channel_author}}
                </div>
            </div>

            <div class="c-chat-card__controls">
                <a class="c-chat-card__enter-button js-join-channel"
                    to_chanel="<?php echo $chanel->id;?>"
                    href="<?php echo $url; ?>"
                >
                    <svg class="icon-nw icon-nw-open-in-new-black-24" viewBox="0 0 24 24">
                        <path d="M0 0h24v24H0V0z" fill="none"/>
                        <path d="M19 19H5V5h7V3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z"/>
                    </svg>

                    Open
                </a>
            </div>
        </div>
    </div>
<?php endforeach; ?>

    <script type="text/javascript">
        window.to_chanel = {
            to_chanel: false,
            date: false,
        };

        $(function() {
            $('.js-join-channel').on('click', function(e) {
                e.preventDefault();

                window.to_chanel = {
                    to_chanel: false,
                    date: false,
                };

                send_message_from_user_chanel(this);
            });

            $(".join_chanel").bind("click",function () {
                    window.to_chanel = { to_chanel : false  , date : false};
                    send_message_from_user_chanel(this);
                 return false;
                }
                );
        });

        function send_message_from_user_chanel(element) {
            window.to_chanel.to_chanel  = $(element).attr("to_chanel");
            $('.message_to_user_area_chanel').val("");
            $(".message_to_user_from_chanel_list").remove();
            var chat_html = '<div class="message_to_user_from_chanel_list" style="display:hide;" title="Enter message" to_chanel='+  to_chanel.to_chanel +'><p class="close_chanel" to_chanel='+to_chanel.to_chanel+'>X</p><div class="message_box" to_chanel='+to_chanel.to_chanel+'></div><div class="chanel" to_chanel='+to_chanel.to_chanel+'><textarea class="message_to_user_area_chanel"  maxlength="500" to_chanel='+to_chanel.to_chanel+'></textarea><button class="submit" class="chanel_button" to_chanel='+to_chanel.to_chanel+'>send</button></div></div>';
            $(".message_to_user_from_chanel_list[to_chanel="+window.to_chanel.to_chanel+"]").remove();
            $('body').append(chat_html);
            $(".message_to_user_from_chanel_list[to_chanel="+window.to_chanel.to_chanel+"]").addClass('new_chanel');
            $(".message_to_user_from_chanel_list[to_chanel="+window.to_chanel.to_chanel+"]").draggable();
            $(".message_to_user_from_chanel_list").bind("click",function() {
               // $(this).addClass("window");
            });
            $(".message_to_user_from_chanel_list").find('button').addClass("message_to_user_from_user_chanel_button");
            $(".message_to_user_from_user_chanel_button").bind("click",function(){
                send_to_chanel();
            });
            $(".close_chanel").bind("click",function(){
                var to_chanel = $(this).attr('to_chanel');
                $(".message_to_user_from_chanel_list[to_chanel="+to_chanel+"]").remove();
                window.to_chanel = { to_chanel : false  , date : false};
            })
            $(".message_to_user_from_chanel_list[to_chanel="+window.to_chanel.to_chanel+"]").show();
            sync_chanel();
        }

        function sync_chanel(){
            $.ajax({
                type: "POST",
                url: "sync/syncchanel",
                dataType: "json",
                data: {to_chanel : window.to_chanel.to_chanel , date : window.to_chanel.date}
            })
                .done(function(data) {
                    $.each(data.chanels_messages, function (index,message) {
                        $(".message_box[to_chanel="+message.to_chanel+"]").append("<p class='old_message'>"+message.first_name+" "+message.second_name+":"+message.message+"</p>");
                        window.to_chanel.date  = message.date;
                        $(".message_box[to_chanel="+message.to_chanel+"]").animate({ scrollTop: 10000}, 200);

                    });
                    setTimeout(sync_chanel, 3000);
                });
        }
        function send_to_chanel(element) {
            var text = $('.message_to_user_area_chanel[to_chanel='+ window.to_chanel.to_chanel+']').val();
            $('.message_to_user_area_chanel[to_chanel='+ window.to_chanel.to_chanel+']').val("");
            $('.message_to_user_from_user_chanel_button[to_chanel='+ window.to_chanel.to_chanel+']').val("");
            $(".message_box[to_chanel="+ window.to_chanel.to_chanel+"]").animate({ scrollTop: 10000}, 50);
            $.ajax({
                type: "POST",
                url: "chanels/addmessagetochanel",
                data : {text :text , to_chanel :  window.to_chanel.to_chanel }
            });
        }
    </script>


