<div class="c-window__scrollable-space">
    <?php foreach ($chanels as $chanel) : ?>
        <div class="c-chat-card">
            <div class="c-chat-card__inner">
            <?php if(isset($chanel['avatar'])) {?>
                <div class="c-chat-card__image-wrap">
                 <img src="<?php echo $chanel['avatar']; ?>" alt="" class="c-chat-card__image">
                </div>
                <?php } ?>

                <div class="c-chat-card__main">
                    <div class="c-chat-card__title">
                        <?php echo $this->escapeHtml($chanel->chanel_name); ?>
                    </div>

                    <div class="c-chat-card__author">
                        <?php echo $chanel->first_name; ?>
                        <?php echo $chanel->second_name; ?>
                    </div>
                </div>

                <div class="c-chat-card__controls">
                    <?php $isConfirmed = $chanel->is_confirmed and $chanel->user_id == $user_id; ?>
                    <?php $isWaiting = !$chanel->pending_response and $chanel->user_id == $user_id; ?>
                    <?php $isAdmin = ($chanel->admins == $user_id) ? true : false; ?>
                    <?php $isClosed = true; ?>
                    <?php if ($isConfirmed or $isAdmin): ?>
                        <a class="c-chat-card__enter-button js-join-private-channel join_chanel_private"
                            to_chanel="<?php echo $chanel->chanel_id; ?>" chanel_name="<?php echo $chanel->chanel_name ?>"
                            href="<?php echo $this->url('chanels', array('action' => 'join_chanel', 'id' => $chanel->chanel_id)); ?>"
                        >
                            <svg class="icon-nw icon-nw-open-in-new-black-24" viewBox="0 0 24 24">
                                <path d="M0 0h24v24H0V0z" fill="none"/>
                                <path d="M19 19H5V5h7V3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z"/>
                            </svg>

                            Open
                        </a>
                    <?php elseif ($isWaiting): ?>
                        <div class="c-chat-card__wait-pseudo-button">
                            <svg class="icon-nw icon-nw-lock-clock-black-24" viewBox="0 0 24 24">
                                <path d="M0 0h24v24H0V0z" fill="none"/>
                                <path d="M6 20V10h12v1c.7 0 1.37.1 2 .29V10c0-1.1-.9-2-2-2h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h6.26c-.42-.6-.75-1.28-.97-2H6zM9 6c0-1.66 1.34-3 3-3s3 1.34 3 3v2H9V6z"/>
                                <path d="M18 13c-2.76 0-5 2.24-5 5s2.24 5 5 5 5-2.24 5-5-2.24-5-5-5zm1.65 7.35L17.5 18.2V15h1v2.79l1.85 1.85-.7.71z"/>
                            </svg>

                            Waiting...
                        </div>
                    <?php elseif ($isClosed): ?>
                        <a class="c-chat-card__request-button js-join-private-channel-request"
                            to_chanel="<?php echo $chanel->chanel_id; ?>"
                            href="<?php echo $this->url('chanels', array('action' => 'join_chanel_request', 'id' => $chanel->chanel_id)); ?>"
                        >
                            <svg class="icon-nw icon-nw-lock-open-black-24" viewBox="0 0 24 24">
                                <path d="M0 0h24v24H0V0z" fill="none"/>
                                <path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6h2c0-1.66 1.34-3 3-3s3 1.34 3 3v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm0 12H6V10h12v10zm-6-3c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2z"/>
                            </svg>

                            Request access
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>

    <?php endforeach; ?>
</div>


<script type="text/javascript">
    window.to_chanel_private = {to_chanel: false, date: false};
    $(function () {
        $('.js-join-private-channel-request').on('click', function(e) {
            e.preventDefault();
            send_to_chanel_request(this);
        });

        $('.js-join-private-channel').on('click', function(e) {
            e.preventDefault();

            window.to_chanel_private = {
                to_chanel: false,
                date: false,
            };

            send_message_from_private_chanel(this);
        });
    });

    function send_to_chanel_request(element) {
        var to_chanel = $(element).attr("to_chanel");
        $.ajax({
            type: "POST",
            url: "chanels/chanelRequest",
            dataType: "json",
            data: {to_chanel: to_chanel}
        })
            .done(function (data) {
                // alert(data);
            });
    }
    function send_message_from_private_chanel(element) {
        window.to_chanel_private.to_chanel = $(element).attr("to_chanel");
        var chanel_name =  $(element).attr("chanel_name");
        $('.message_to_user_area_chanel').val("");
        var chat_html = '<div class="abs window" id="chat_private"><div class="abs window_inner"><div class="window_top"><span class="float_left">Chat :'+chanel_name+'</span><span class="float_right"><a href="#" class="window_min"></a><a href="#" class="window_resize"></a><a href="#icon_dock_drive" class="window_close"></a></span></div><div class="abs window_content">' +

            '<div class="message_to_user_from_chanel_list" style="display:hide;" title="Enter message" to_chanel=' + to_chanel_private.to_chanel + '>' +
            '<div class="message_box" to_chanel=' + to_chanel_private.to_chanel + '>' +
            '</div><div class="chanel" style="width:440px;margin-left: 10px" to_chanel=' + to_chanel_private.to_chanel + '>' +
            
            '<div class="message_to_user_area_chanel" id="private_chat_message"  to_chanel=' + to_chanel_private.to_chanel + '></div>' +
            '<button class="submit" class="chanel_button" to_chanel=' + window.to_chanel_private.to_chanel + '>Send</button>' +
            '</div></div>' + '</div> <div class="abs window_bottom">Chat</div> </div> <span class="abs ui-resizable-handle ui-resizable-se"></span> </div>';;

        $("#chat_private").remove();
        $('body').append(chat_html);
        CKEDITOR.replace('private_chat_message',{
            width:750,
            height:205,
            resize_enabled:true
        });
        $(".message_to_user_from_chanel_list").find('button').addClass("message_to_user_from_user_chanel_button");
        $(".message_to_user_from_user_chanel_button").bind("click", function () {
            send_to_chanel_private();
        });
        $(".message_to_user_from_chanel_list[to_chanel=" + window.to_chanel_private.to_chanel + "]").show();
        $("#chat_private").show();
        sync_chanel_private();
    }

    function sync_chanel_private() {
        $.ajax({
            type: "POST",
            url: "sync/syncchanelprivate",
            dataType: "json",
            data: {to_chanel: window.to_chanel_private.to_chanel, date: window.to_chanel_private.date}
        })
            .done(function (data) {
                $.each(data, function (index, message) {
                    let to_chanel  = parseInt(message.to_chanel);
                    $(".message_box[to_chanel=" + to_chanel + "]").append("<p class='old_message allowSelectOneClick'>" + message.first_name + " " + message.second_name + ":" + message.message + "</p>");
                    if (typeof message.date !== "undefined") {
                        window.to_chanel_private.date = message.date;
                    }
                    //$(".message_box[to_chanel=" + message.to_chanel + "]").animate({scrollTop: 10000}, 200);
                });
                setTimeout(sync_chanel_private, 3000);
            });
    }

    function send_to_chanel_private(element) {
        var text = CKEDITOR.instances.private_chat_message.getData();
        $('.message_to_user_area_chanel[to_chanel=' + window.to_chanel_private.to_chanel + ']').val("");
        $('.message_to_user_from_user_chanel_button[to_chanel=' + window.to_chanel_private.to_chanel + ']').val("");
        $(".message_box[to_chanel=" + window.to_chanel_private.to_chanel + "]").animate({scrollTop: 10000}, 50);
        $.ajax({
            type: "POST",
            url: "chanels/addmessagetochanel",
            data: {text: text, to_chanel: window.to_chanel_private.to_chanel}
        });
    }
</script>


