    <?php foreach ($chanels as $chanel) : ?>
            <?php echo $this->escapeHtml($chanel->chanel_name);?>
                <a class="join_chanel" to_chanel="<?php echo  $chanel->id;?>" href="<?php echo $this->url('chanels',
                    array('action'=>'join_chanel', 'id' => $chanel->id));?>">Join</a>
        <br/>
    <?php  endforeach; ?>
    <script type="text/javascript">
        window.to_chanel = { to_chanel : false  , date : false};
        $(function() {
            $(".join_chanel").bind("click",function () {
                    window.to_chanel = { to_chanel : false  , date : false};
                    send_message_from_user_chanel(this);
                 return false;
                }
                );
        });

        function send_message_from_user_chanel(element) {
            window.to_chanel.to_chanel  = $(element).attr("to_chanel");
            $('.message_to_user_area_chanel').val("");
            $(".message_to_user_from_chanel_list").remove();
            var chat_html = '<div class="message_to_user_from_chanel_list" style="display:hide;" title="Enter message" to_chanel='+  to_chanel.to_chanel +'><p class="close_chanel" to_chanel='+to_chanel.to_chanel+'>X</p><div class="message_box" to_chanel='+to_chanel.to_chanel+'></div><div class="chanel" to_chanel='+to_chanel.to_chanel+'><textarea class="message_to_user_area_chanel"  maxlength="500" to_chanel='+to_chanel.to_chanel+'></textarea><button class="submit" class="chanel_button" to_chanel='+to_chanel.to_chanel+'>send</button></div></div>';
            $(".message_to_user_from_chanel_list[to_chanel="+window.to_chanel.to_chanel+"]").remove();
            $('body').append(chat_html);
            $(".message_to_user_from_chanel_list[to_chanel="+window.to_chanel.to_chanel+"]").addClass('new_chanel');
            $(".message_to_user_from_chanel_list[to_chanel="+window.to_chanel.to_chanel+"]").draggable();
            $(".message_to_user_from_chanel_list").bind("click",function() {
               // $(this).addClass("window");
            });
            $(".message_to_user_from_chanel_list").find('button').addClass("message_to_user_from_user_chanel_button");
            $(".message_to_user_from_user_chanel_button").bind("click",function(){
                send_to_chanel();
            });
            $(".close_chanel").bind("click",function(){
                var to_chanel = $(this).attr('to_chanel');
                $(".message_to_user_from_chanel_list[to_chanel="+to_chanel+"]").remove();
                window.to_chanel = { to_chanel : false  , date : false};
            })
            $(".message_to_user_from_chanel_list[to_chanel="+window.to_chanel.to_chanel+"]").show();
            sync_chanel();
        }

        function sync_chanel(){
            $.ajax({
                type: "POST",
                url: "sync/syncchanel",
                dataType: "json",
                data: {to_chanel : window.to_chanel.to_chanel , date : window.to_chanel.date}
            })
                .done(function(data) {
                    $.each(data.chanels_messages, function (index,message) {
                        $(".message_box[to_chanel="+message.to_chanel+"]").append("<p class='old_message'>"+message.first_name+" "+message.second_name+":"+message.message+"</p>");
                        window.to_chanel.date  = message.date;
                        $(".message_box[to_chanel="+message.to_chanel+"]").animate({ scrollTop: 10000}, 200);

                    });
                    setTimeout(sync_chanel, 3000);
                });
        }
        function send_to_chanel(element) {
            var text = $('.message_to_user_area_chanel[to_chanel='+ window.to_chanel.to_chanel+']').val();
            $('.message_to_user_area_chanel[to_chanel='+ window.to_chanel.to_chanel+']').val("");
            $('.message_to_user_from_user_chanel_button[to_chanel='+ window.to_chanel.to_chanel+']').val("");
            $(".message_box[to_chanel="+ window.to_chanel.to_chanel+"]").animate({ scrollTop: 10000}, 50);
            $.ajax({
                type: "POST",
                url: "chanels/addmessagetochanel",
                data : {text :text , to_chanel :  window.to_chanel.to_chanel }
            });
        }
    </script>


