<!-- TODO: Don't delete! Temporarily stopped here.
<div class="c-chat-card">
    <div class="c-chat-card__inner">
        <div class="c-chat-card__image-wrap">
            <img src="https://www.fillmurray.com/360/360" alt="" class="c-chat-card__image">
        </div>

        <div class="c-chat-card__main">
            <div class="c-chat-card__title">
                Some channel name
            </div>

            <div class="c-chat-card__author">
                {{channel_author}}
            </div>
        </div>

        <div class="c-chat-card__controls">
            <button class="c-chat-card__enter-button" type="button">
                <svg class="icon-nw icon-nw-open-in-new-black-24" viewBox="0 0 24 24">
                    <path d="M0 0h24v24H0V0z" fill="none"/>
                    <path d="M19 19H5V5h7V3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z"/>
                </svg>

                Open
            </button>

            <button class="c-chat-card__request-button" type="button">
                <svg class="icon-nw icon-nw-lock-open-black-24" viewBox="0 0 24 24">
                    <path d="M0 0h24v24H0V0z" fill="none"/>
                    <path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6h2c0-1.66 1.34-3 3-3s3 1.34 3 3v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm0 12H6V10h12v10zm-6-3c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2z"/>
                </svg>

                Request access
            </button>

            <div class="c-chat-card__wait-pseudo-button">
                <svg class="icon-nw icon-nw-lock-clock-black-24" viewBox="0 0 24 24">
                    <path d="M0 0h24v24H0V0z" fill="none"/>
                    <path d="M6 20V10h12v1c.7 0 1.37.1 2 .29V10c0-1.1-.9-2-2-2h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h6.26c-.42-.6-.75-1.28-.97-2H6zM9 6c0-1.66 1.34-3 3-3s3 1.34 3 3v2H9V6z"/>
                    <path d="M18 13c-2.76 0-5 2.24-5 5s2.24 5 5 5 5-2.24 5-5-2.24-5-5-5zm1.65 7.35L17.5 18.2V15h1v2.79l1.85 1.85-.7.71z"/>
                </svg>

                Waiting...
            </div>
        </div>
    </div>
</div>
-->

<div class="c-window__scrollable-space">
    <?php foreach ($chanels as $chanel) : ?>
        <div class="c-chat-card">
            <div class="c-chat-card__inner">
                <div class="c-chat-card__image-wrap">
                    <img src="https://www.fillmurray.com/360/360" alt="" class="c-chat-card__image">
                </div>

                <div class="c-chat-card__main">
                    <div class="c-chat-card__title">
                        <?php echo $this->escapeHtml($chanel->chanel_name); ?>
                    </div>

                    <div class="c-chat-card__author">
                        <?php echo $chanel->first_name; ?>
                        <?php echo $chanel->second_name; ?>
                    </div>
                </div>

                <div class="c-chat-card__controls">
                    <?php $isConfirmed = $chanel->is_confirmed and $chanel->user_id == $user_id; ?>
                    <?php $isWaiting = !$chanel->pending_response and $chanel->user_id == $user_id; ?>
                    <?php $isAdmin = ($chanel->admins == $user_id) ? true : false; ?>
                    <?php $isClosed = true; ?>
                    <?php if ($isConfirmed or $isAdmin): ?>
                        <a class="c-chat-card__enter-button js-join-private-channel join_chanel_private"
                            to_chanel="<?php echo $chanel->chanel_id; ?>"
                            href="<?php echo $this->url('chanels', array('action' => 'join_chanel', 'id' => $chanel->chanel_id)); ?>"
                        >
                            <svg class="icon-nw icon-nw-open-in-new-black-24" viewBox="0 0 24 24">
                                <path d="M0 0h24v24H0V0z" fill="none"/>
                                <path d="M19 19H5V5h7V3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z"/>
                            </svg>

                            Open
                        </a>
                    <?php elseif ($isWaiting): ?>
                        <div class="c-chat-card__wait-pseudo-button">
                            <svg class="icon-nw icon-nw-lock-clock-black-24" viewBox="0 0 24 24">
                                <path d="M0 0h24v24H0V0z" fill="none"/>
                                <path d="M6 20V10h12v1c.7 0 1.37.1 2 .29V10c0-1.1-.9-2-2-2h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h6.26c-.42-.6-.75-1.28-.97-2H6zM9 6c0-1.66 1.34-3 3-3s3 1.34 3 3v2H9V6z"/>
                                <path d="M18 13c-2.76 0-5 2.24-5 5s2.24 5 5 5 5-2.24 5-5-2.24-5-5-5zm1.65 7.35L17.5 18.2V15h1v2.79l1.85 1.85-.7.71z"/>
                            </svg>

                            Waiting...
                        </div>
                    <?php elseif ($isClosed): ?>
                        <a class="c-chat-card__request-button js-join-private-channel-request"
                            to_chanel="<?php echo $chanel->chanel_id; ?>"
                            href="<?php echo $this->url('chanels', array('action' => 'join_chanel_request', 'id' => $chanel->chanel_id)); ?>"
                        >
                            <svg class="icon-nw icon-nw-lock-open-black-24" viewBox="0 0 24 24">
                                <path d="M0 0h24v24H0V0z" fill="none"/>
                                <path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6h2c0-1.66 1.34-3 3-3s3 1.34 3 3v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm0 12H6V10h12v10zm-6-3c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2z"/>
                            </svg>

                            Request access
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
</div>

<!--        <hr><br>New<br>-->
<!--        --><?php
//   // var_dump($chanel);
//    echo $this->escapeHtml($chanel->chanel_name); ?>
<!--        <a class="join_chanel_request" to_chanel="--><?php //echo $chanel->chanel_id; ?><!--"-->
<!--           href="--><?php //echo $this->url('chanels',
//               array('action' => 'join_chanel_request', 'id' => $chanel->chanel_id)); ?><!--">Make Request</a>-->
<!--  --><?php //if ($chanel->pending_response)  {  ?>
<!--        <h3>Waiting</h3>-->
<!--  --><?php //}?>
<!---->
<!---->
<!--        --><?php
//      if($chanel->is_confirmed and $chanel->user_id == $user_id) {
//        ?>
<!--        <a class="join_chanel_private" to_chanel="--><?php //echo $chanel->chanel_id; ?><!--" href="-->
<!--                      --><?php
//        echo $this->url('chanels',
//            array('action' => 'join_chanel', 'id' => $chanel->chanel_id)); ?><!--">Join Chanel</a>-->
<!--        --><?php
//    }
//    if(!$chanel->is_confirmed and $chanel->user_id == $user_id) {
//       echo "please wait";
//    }
//    ?>
<!--    <br/>-->

<!--        <hr><br>Old<br>-->
<!---->
<!--            <a class="join_chanel_request" to_chanel="--><?php //echo $chanel->chanel_id; ?><!--" href="--><?php //echo $this->url('chanels', array('action' => 'join_chanel_request', 'id' => $chanel->chanel_id)); ?><!--">-->
<!--               Make Request-->
<!--            </a>-->
<!--            --><?php //if($chanel->confirmed and $chanel->user_id == $user_id) { ?>
<!--                <a class="join_chanel_private" to_chanel="--><?php //echo $chanel->chanel_id; ?><!--" href="--><?php //echo $this->url('chanels', array('action' => 'join_chanel', 'id' => $chanel->chanel_id)); ?><!--"-->
<!--                >-->
<!--                    Join Chanel-->
<!--                </a>-->
<!--            --><?php //} if(!$chanel->confirmed and $chanel->user_id == $user_id) {
//                echo "please wait";
//            } ?>
    <?php endforeach; ?>


<script type="text/javascript">
    window.to_chanel_private = {to_chanel: false, date: false};
    $(function () {
        // $(".join_chanel_request").bind("click", function () {
        //         send_to_chanel_request(this);
        //         return false;
        //     }
        // );

        // $(".join_chanel_private").bind("click", function () {
        //     window.to_chanel_private = {to_chanel: false, date: false};
        //     send_message_from_private_chanel(this);
        //     return false;
        // }
        // );

        $('.js-join-private-channel-request').on('click', function(e) {
            e.preventDefault();
            send_to_chanel_request(this);
        });

        $('.js-join-private-channel').on('click', function(e) {
            e.preventDefault();

            window.to_chanel_private = {
                to_chanel: false,
                date: false,
            };

            send_message_from_private_chanel(this);
        });
    });

    function send_to_chanel_request(element) {
        var to_chanel = $(element).attr("to_chanel");
        $.ajax({
            type: "POST",
            url: "chanels/chanelRequest",
            dataType: "json",
            data: {to_chanel: to_chanel}
        })
            .done(function (data) {
                // alert(data);
            });
    }
    function send_message_from_private_chanel(element) {
        window.to_chanel_private.to_chanel = $(element).attr("to_chanel");
        $('.message_to_user_area_chanel').val("");
        $(".message_to_user_from_chanel_list").remove();
        var chat_html = '<div class="abs window" id="chat_private"><div class="abs window_inner"><div class="window_top"><span class="float_left">Chat</span><span class="float_right"><a href="#" class="window_min"></a><a href="#" class="window_resize"></a><a href="#icon_dock_drive" class="window_close"></a></span></div><div class="abs window_content">' +

            '<div class="message_to_user_from_chanel_list" style="display:hide;" title="Enter message" to_chanel=' + to_chanel_private.to_chanel + '>' +
            '<p class="close_chanel" to_chanel=' + to_chanel_private.to_chanel + '>X</p>' +
            '<div class="message_box" to_chanel=' + to_chanel_private.to_chanel + '>' +
            '</div><div class="chanel" to_chanel=' + to_chanel_private.to_chanel + '>' +
            '<textarea class="message_to_user_area_chanel"  maxlength="500" to_chanel=' + to_chanel_private.to_chanel + '></textarea>' +
            '<button class="submit" class="chanel_button" to_chanel=' + window.to_chanel_private.to_chanel + '>Send</button>' +
            '</div></div>' + '</div> <div class="abs window_bottom">Chat</div> </div> <span class="abs ui-resizable-handle ui-resizable-se"></span> </div>';;

        $(".message_to_user_from_chanel_list[to_chanel=" + window.to_chanel_private.to_chanel + "]").remove();
        $('body').append(chat_html);
        // $(".message_to_user_from_chanel_list[to_chanel=" + window.to_chanel_private.to_chanel + "]").addClass('new_chanel');
        // $(".message_to_user_from_chanel_list[to_chanel=" + window.to_chanel_private.to_chanel + "]").draggable();
        $(".message_to_user_from_chanel_list").find('button').addClass("message_to_user_from_user_chanel_button");
        $(".message_to_user_from_user_chanel_button").bind("click", function () {
            send_to_chanel_private();
        });
        $(".close_chanel").bind("click", function () {
            var to_chanel = $(this).attr('to_chanel');
            $(".message_to_user_from_chanel_list[to_chanel=" + to_chanel + "]").remove();
            window.to_chanel_private = {to_chanel: false, date: false};
        })
        $(".message_to_user_from_chanel_list[to_chanel=" + window.to_chanel_private.to_chanel + "]").show();
        $("#chat_private").show();
        sync_chanel_private();
    }

    function sync_chanel_private() {
        $.ajax({
            type: "POST",
            url: "sync/syncchanelprivate",
            dataType: "json",
            data: {to_chanel: window.to_chanel_private.to_chanel, date: window.to_chanel_private.date}
        })
            .done(function (data) {
                $.each(data, function (index, message) {
                    $(".message_box[to_chanel=" + message.to_chanel + "]").append("<p class='old_message'>" + message.first_name + " " + message.second_name + ":" + message.message + "</p>");
                    if (typeof message.date !== "undefined") {
                        window.to_chanel_private.date = message.date;
                    }
                    $(".message_box[to_chanel=" + message.to_chanel + "]").animate({scrollTop: 10000}, 200);
                });
                setTimeout(sync_chanel_private, 3000);
            });
    }

    function send_to_chanel_private(element) {
        var text = $('.message_to_user_area_chanel[to_chanel=' + window.to_chanel_private.to_chanel + ']').val();
        $('.message_to_user_area_chanel[to_chanel=' + window.to_chanel_private.to_chanel + ']').val("");
        //  $(".message_box[to_chanel="+ window.to_chanel_private.to_chanel+"]").append("you:"+text+"<br/>");
        $('.message_to_user_from_user_chanel_button[to_chanel=' + window.to_chanel_private.to_chanel + ']').val("");
        $(".message_box[to_chanel=" + window.to_chanel_private.to_chanel + "]").animate({scrollTop: 10000}, 50);
        $.ajax({
            type: "POST",
            url: "chanels/addmessagetochanel",
            data: {text: text, to_chanel: window.to_chanel_private.to_chanel}
        });
    }
</script>


