<div id="window_admins" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
          <span class="float_left">
           Administration
          </span>
          <span class="float_right">
            <a href="#" class="window_min"></a>
            <a href="#" class="window_resize"></a>
            <a href="#icon_dock_drive" class="window_close"></a>
          </span>
        </div>
        <div class="abs window_content" id="admins_content">



        </div>
        <div class="abs window_bottom">
            Administration
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
