<div id="window_admins" class="c-window r-border-box-area abs window">
    <div class="c-window__inner _abs window_inner">
        <div class="c-window__title-bar window_top">
            <div class="c-window__title float_left">
                Email
            </div>
            <div class="float_right">
                <a href="#" class="window_min"></a>
                <a href="#" class="window_resize"></a>
                <a href="#icon_dock_blogs" class="window_close"></a>
            </div>
        </div>


        <div class="c-window__main _abs _window_content" id="admins_content">
<iframe src="http://mail.octopus.local/" height="850" width="1000" title="Email"></iframe>
        </div>

        <div class="c-window__status-bar _abs _window_bottom">
            <div class="c-window__status-text">
                Email
            </div>
        </div>
    </div>

    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
