<div id="window_blogs" class="c-window r-border-box-area abs window">
    <div class="c-window__inner _abs window_inner">
        <div class="c-window__title-bar window_top">
            <div class="c-window__title float_left">
                Blogs
            </div>

            <span class="float_right">
                <a href="#" class="window_min"></a>
                <a href="#" class="window_resize"></a>
                <a href="#icon_dock_drive" class="window_close"></a>
            </span>
        </div>

        <div class="c-window__main _abs _window_content" id="notes_content">
            <!--
            <div class="c-window__aside window_aside">
                Notes
            </div>
            -->

            <div class="c-window__tabs-wrap is-vertical-navigation _abs _window_content" id="notes_tabs">
                <div class="c-window__tabs window_main user-tabs">
                    <ul class="c-window__tabs-inner">
                        <li class="c-window__tab"><a class="users-tab-link" href="#list_blogs">Posts</a></li>
                        <li class="c-window__tab"><a class="users-tab-link" href="#new_blog">Create Post</a></li>
                    </ul>
                </div>

                <div class="c-window__tab-content" id="list_blogs"></div>
                <div class="c-window__tab-content" id="new_blog"></div>

                <script type="text/javascript" src="js/pages/main/blogs.js"></script>
            </div>
        </div>

        <div class="c-window__status-bar _abs _window_bottom">
            <div class="c-window__status-text">
                Some text
            </div>
        </div>
    </div>

    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
