<div id="window_drive" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
            <span class="float_left">
                <img class="parent_directory" dir_key='0' src="assets/images/gui/left.png"/>
                <img src="assets/images/icons/icon_16_drive.png"/>
                Hard Drive
            </span>
            <span class="float_right">
                <a href="#" class="window_min"></a>
                <a href="#" class="window_resize"></a>
                <a href="#icon_dock_drive" class="window_close"></a>
            </span>
        </div>
        <div class="abs window_content">
            <div class="window_main" id="hard_drive">
            </div>

            <script type="text/javascript" src="js/pages/main/files.js"></script>
        </div>
        <div class="abs window_bottom">
            Storage in use: 119.1 GB
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
