<div id="window_frame" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
            <span class="float_left">
                <img src="assets/images/icons/iframe50.png"/>
                Фреймы
            </span>
            <span class="float_right">
                <a href="#" class="window_min"></a>
                <a href="#" class="window_resize"></a>
                <a href="#icon_dock_frame" class="window_close"></a>
            </span>
        </div>
        <div class="abs window_content">
            <div class="container">
                <p class="frame_string">Window url <input class="frame_input" type="text" name="frame_url"
                                                          id="frame_url"/></p>
                <p class="frame_string">Window name <input class="frame_input" type="text" name="frame_name"
                                                           id="frame_name"/></p>
                <p class="frame_string">Window Image <input class="frame_input" type="file" name="frame_image"
                                                            id="frame_image"/></p>
                <p class="frame_string"><input type="button" value="save" id="save_frame" class="frame_input"
                                               style="float: left;"></p>
            </div>
            <div class="frame_container">

            </div>
        </div>
        <div class="abs window_bottom">
            Фреймы
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
<div id="window_frame_container" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
            <span class="float_left">
                <img src="assets/images/icons/iframe50.png"/>
                Фреймы
            </span>
            <span class="float_right">

                <a href="#" class="window_min"></a>
                <a href="#" class="window_resize"></a>
                <a href="#icon_dock_drive" class="window_close"></a>
            </span>
        </div>
        <div class="frame_container_output">
        </div>
        <div class="abs window_bottom">
            Фреймы
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
<script type="text/javascript">
    function load_frames() {
        $.get("frames/loadFrames")
            .done(function (data) {
                $(".frame_container").html(data);
            });
    }

    $(function () {
        load_frames();
        $("#save_frame").on("click", function () {
            const frame_url = $("#frame_url").val();
            const frame_name = $("#frame_name").val();
            const image = $("#frame_image").prop("files");
            var file = image[0];
            var data = new FormData();
            data.append('file', file);
            data.append('frame_url', frame_url);
            data.append('frame_name', frame_name);
            var url = "frames/saveFrame";
            var request = new XMLHttpRequest();
            var xmlupload = request.upload;
            xmlupload.addEventListener('load', load_frames, false);
            request.open("POST", url, true);
            request.send(data);
        });
    });


</script>
