<div id="window_messages" class="c-window r-border-box-area abs window">
    <div class="c-window__inner _abs window_inner">

        <div class="c-window__title-bar window_top">
            <div class="c-window__title float_left">
                Messages
            </div>

            <div class="c-window__window-controls float_right">
            <span class="float_right">
                <a href="#" class="window_min"></a>
                <a href="#" class="window_resize"></a>
                <a href="#icon_dock_drive" class="window_close"></a>
            </span>
            </div>
        </div>




        <div class="c-window__main _abs _window_content" id="messages_content">


            <div class="c-window__tabs-wrap is-vertical-navigation _abs _window_content" id="messages_tabs">


                <div class="c-window__tabs window_main user-tabs">
                    <ul class="c-window__tabs-inner">
                        <li class="c-window__tab"><a class="users-tab-link" href="#chats">Chats</a></li>
                        <li class="c-window__tab"><a class="users-tab-link" href="#chanels">Channels</a></li>
                        <li class="c-window__tab"><a class="users-tab-link" href="#private_chanels">Private Channels</a></li>
                        <li class="c-window__tab"><a class="users-tab-link" href="#private_chanels_admin">Private Channels Settings</a></li>
                        <li class="c-window__tab"><a class="users-tab-link" href="#create_chanel">Create Channel</a></li>
                    </ul>
                </div>





                <div class="c-window__tab-content" id="chats">
                    <script type="text/javascript" src="js/pages/main/messages.js"></script>
                </div>

                <div class="c-window__tab-content" id="chanels">
                    <script type="text/javascript" src="js/pages/main/chanels.js"></script>
                </div>

                <div class="c-window__tab-content" id="private_chanels">
                    <script type="text/javascript" src="js/pages/main/private_chanels.js"></script>
                </div>

                 <div class="c-window__tab-content" id="create_chanel">
                    <div class="c-window__scrollable-space">
                        <div class="c-create-channel">
                            <div class="c-create-channel__header">
                                Create channel
                            </div>

                            <div class="c-create-channel__main">
                                <div class="c-create-channel__row">
                                    <input class="c-field" name="chanel_name" type="text" id="chanel_name" placeholder="Channel name">
                                </div>

                                <div class="c-create-channel__row">
                                    <div>
                                        <label class="c-checkbox" for="is_private">
                                            <input class="c-checkbox__input" name="is_private" type="checkbox" id="is_private">

                                            <div class="c-checkbox__icon"></div>

                                            <div class="c-checkbox__text">
                                                Is private channel
                                            </div>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="c-create-channel__footer">
                                <button class="c-button c-create-channel__create-button" id="create_chanel_submit">
                                    <svg class="icon-nw icon-nw-forum-black-24" viewBox="0 0 24 24">
                                        <path d="M0 0h24v24H0V0z" fill="none" />
                                        <path d="M15 4v7H5.17L4 12.17V4h11m1-2H3c-.55 0-1 .45-1 1v14l4-4h10c.55 0 1-.45 1-1V3c0-.55-.45-1-1-1zm5 4h-2v9H6v2c0 .55.45 1 1 1h11l4 4V7c0-.55-.45-1-1-1z" />
                                    </svg>

                                    Create
                                </button>
                            </div>
                        </div>
                    </div>

                    <script type="text/javascript" src="js/pages/main/create_chanel.js"></script>
                </div>

                <div class="c-window__tab-content" id="private_chanels_admin">
                    <script type="text/javascript" src="js/pages/main/private_chanels_admin.js"></script>
                </div>

            </div>
        </div>



        <div class="c-window__status-bar _abs _window_bottom">
            <div class="c-window__status-text">
                Some text
            </div>

        </div>


    </div>

    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
