<div id="window_money" class="abs  window">
	<div class="abs window_inner">
		<div class="window_top">
			<span class="float_left"> <img src="assets/images/icons/3.png" />
				Tasks
			</span> <span class="float_right"> <a href="#" class="window_min"></a>
				<a href="#" class="window_resize"></a> <a href="#icon_dock_drive"
				class="window_close"></a>
			</span>
		</div>
		<div class="window_content abs" id="tasks_content">
			<div id="tasks_tabs" class="window_main">
				<span id="go_to_projects">Go To Projects</span>

				<script type="text/javascript">

                    $("#go_to_projects").bind("click", function () {
                        refresh_boards();
                    });
                </script>
				<div id="tasks_transaction">
					<script type="text/javascript" src="js/pages/main/tasks_window.js"></script>
				</div>

			</div>
		</div>
		<div class="abs window_bottom">Task Manager</div>
	</div>
	<span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
<div id="task_popup" class="abs  window">
	<div class="abs window_inner">
		<div class="window_top">
			<span class="float_left"> <img src="assets/images/icons/3.png" />
				Tasks
			</span> <span class="float_right"> <a href="#" class="window_min"></a>
				<a href="#" class="window_resize"></a> <a href="#icon_dock_drive"
				class="window_close"></a>
			</span>
		</div>
		<div class="window_content abs" id="task_create">
			<hr>
			<h4>Create Task</h4>
			<h5>Members List</h5>
			<div id="members_list"></div>
			<div id="task_members_list"></div>

			<div id="task_name_container">
				<h5>Task Name</h5>
				<input type="text" name="task_name" placeholder="Task name"
					id="task_name">
			</div>
			<div>
				<h5>Estimation in hours</h5>
				<input type="text" name="task_estimation"
					placeholder="Estimation in hours" id="task_estimate">
			</div>
			<div>
				<input type="hidden" name="task_members" placeholder="task members"
					id="task_members">
				<h5>Task Description</h5>
				<div class="description">
					<div id="task_description_field"></div>
				</div>
			</div>
			<div>
				<h5>Attach Files</h5>
				<svg class="icon-nw icon-nw-attach-file-16" viewBox="0 0 16 16"
					id="task_file_ocon">
            <path fill-rule="evenodd" clip-rule="evenodd"
						d="m14.8 7.6-5.5 6.3c-2.1 2.4-5.6 2.8-7.7.7-2.1-2.1-2-5.8.1-8.2L7 .4c.3-.4.9-.4 1.3-.1.4.4.3 1 0 1.4L3 7.7c-1.5 1.7-1.5 4.1-.1 5.5 1.4 1.4 3.7 1.2 5.2-.5l5.5-6.3c.9-1 .9-2.6.1-3.4-.8-.8-2.3-.7-3.2.3L5.4 9c-.4.4-.4 1-.1 1.3.3.3.8.3 1.2-.1l4.8-5.5c.3-.4.9-.5 1.3-.1s.3 1 0 1.4l-4.8 5.5c-1 1.2-2.7 1.3-3.7.3s-1-2.8.1-4l5-5.7c1.6-1.8 4.1-2.1 5.7-.5 1.5 1.4 1.5 4.2-.1 6z"></path>
        </svg>
				<input type="file" name="task_file[]" class="action_btn" multiple
					placeholder="task file" id="task_file_input">
			</div>
			<div>
				<input type="button" value="save task" id="save_task"
					class="action_btn"
					project_id='<?php if (isset($board["project_id"])) echo $board["project_id"] ?>' />
			</div>
		</div>
	</div>
</div>