<div id="window_network" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
            <img id="go_to_network" dir_key='0' src="assets/images/gui/left.png"/>
            <img id="get_parent_directory" dir_key='0' src="assets/images/icons/up-24.png"/>
<!--            <img src="assets/images/icons/network_icon_inner.png"/>-->
                Network
            <script type="text/javascript">
                $("#go_to_network").bind("click", function () {
                    refresh_network();
                });
            </script>
            <span class="float_right">
                <a href="#" class="window_min"></a>
                <a href="#" class="window_resize"></a>
                <a href="#icon_dock_drive" class="window_close"></a>
            </span>
        </div>
        <div class="abs window_content">
            <div class="window_main" id="network_frame">

            </div>
            <script type="text/javascript" src="js/pages/main/network.js"></script>

        </div>
        <div class="abs window_bottom">
            Network
        </div>
</div>

<span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
