<div id="window_network" class="c-window r-border-box-area abs window">
    <div class="c-window__inner _abs window_inner">
        <div class="c-window__title-bar window_top">
            <img id="go_to_network" dir_key='0' src="assets/images/gui/left.png"/>
<!--            <img src="assets/images/icons/network_icon_inner.png"/>-->
                Network
            <script type="text/javascript">
                $("#go_to_network").bind("click", function () {
                    refresh_network();
                });
            </script>
            <div class="c-window__window-controls float_right">
                <a class="c-window__window-control window_min" href="#">
                    <svg class="icon-nw icon-nw-window-rollup-16" viewBox="0 0 16 16">
                        <path d="M14.5 14h-13c-.4 0-.8-.3-.8-.8s.3-.8.8-.8h13c.4 0 .8.3.8.8s-.4.8-.8.8z"/>
                    </svg>
                </a>
                <a class="c-window__window-control window_resize" href="#">
                    <svg class="icon-nw icon-nw-window-maximize-16" viewBox="0 0 16 16">
                        <path
                            d="M12 1H4C2.3 1 1 2.3 1 4v8c0 1.7 1.3 3 3 3h8c1.7 0 3-1.3 3-3V4c0-1.7-1.3-3-3-3zm1.5 11c0 .8-.7 1.5-1.5 1.5H4c-.8 0-1.5-.7-1.5-1.5V4c0-.8.7-1.5 1.5-1.5h8c.8 0 1.5.7 1.5 1.5v8z"/>
                    </svg>
                </a>
                <a class="c-window__window-control window_close" href="#icon_dock_messages" id="close_messages">
                    <svg class="icon-nw icon-nw-window-close-16" viewBox="0 0 16 16">
                        <path
                            d="M14.5 13.5c.3.3.3.8 0 1.1-.2.1-.3.2-.5.2s-.4-.1-.5-.2L8 9.1l-5.5 5.5c-.2.1-.3.2-.5.2s-.4-.1-.5-.2c-.3-.3-.3-.8 0-1.1L6.9 8 1.5 2.5c-.3-.3-.3-.8 0-1.1.3-.3.8-.3 1.1 0L8 6.9l5.5-5.5c.3-.3.8-.3 1.1 0 .3.3.3.8 0 1.1L9.1 8l5.4 5.5z"/>
                    </svg>
                </a>
            </div>
        </div>
        <div class="c-window__main _abs _window_content" id="network_frame">
            <div class="c-window__tab-content" id="network">
                            <script type="text/javascript" src="js/pages/main/network.js"></script>
            </div>
        </div>
    <div class="c-window__status-bar _abs _window_bottom">
        <div class="c-window__status-text">
            Some text
        </div>
    </div>
</div>

<span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
