<div id="window_network" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
            <span class="float_left">
                <img src="assets/images/icons/icon_16_network.png"/>
            </span>
            <span class="float_right">
                <a href="#" class="window_min"></a>
                <a href="#" class="window_resize"></a>
                <a href="#icon_dock_network" class="window_close"></a>
            </span>
        </div>
        <div id="network_frame">
            <span id="go_to_network">Go To Network</span>
            <script type="text/javascript">
                $("#go_to_network").bind("click", function () {
                    refresh_network();
                });
            </script>
            <div class="abs" id="network">
            </div>
        </div>

        <script type="text/javascript" src="js/pages/main/network.js"></script>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
