<div id="window_payment" class="abs window_payment window">
    <div class="abs window_inner">
        <div class="window_top">
          <span class="float_left">
            Payment
          </span>
          <span class="float_right">
            <a href="#icon_dock_payment" class="window_close"></a>
          </span>
        </div>
        <div class="abs">
            <div id="accordion_payemnts">

                <h3>Wallet</h3>

                <div id="wallet">
                    test
                </div>
                <script type="text/javascript" src="js/pages/main/wallet.js"></script>
                <h3>Market</h3>

                <div id="Market">
                    <div id="tag_cloud">

                    </div>
                    <script type="text/javascript" src="js/pages/main/tags.js"></script>

                </div>
            </div>

        </div>
    </div>
</div>
