<div id="window_search" class="abs  window">
    <div class="abs window_inner">
        <div class="window_top">
          <span class="float_left">
            Search
          </span>
          <span class="float_right">
            <a href="#" class="window_min"></a>
            <a href="#" class="window_resize"></a>
            <a href="#icon_dock_search" class="window_close" id="close_search"></a>
          </span>
        </div>
        <div class="window_content abs" id="search_content">
            <div class="window_aside">
                Search
            </div>

            <div id="search_tabs" class="abs window_content">
                <div class="window_main user-tabs" >
                <ul>
                    <li><a class="users-tab-link" href="#google_search">Google Search</a></li>
                    <li><a class="users-tab-link" href="#user_search_div">User Search</a></li>
                </ul>
                </div>
                <div id="google_search">
                        <input type="text" id="google_search_input"/>
                        <button value="search" id="google_search_button">search</button>
                </div>
                <div id="user_search_div">
                    <script type="text/javascript" src="js/pages/main/search.js"></script>
                </div>
            </div>
        </div>
        <div class="abs window_bottom">
            Search
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
