<div id="window_settings" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
          <span class="float_left">
            <img src="assets/images/icons/setting_22.png"/>
            Settings
          </span>
            <span class="float_right">
                <a href="#" class="window_min"></a>
                <a href="#" class="window_resize"></a>
                <a href="#icon_dock_drive" class="window_close"></a>
            </span>
        </div>
        <div class="abs window_content" id="settings_content">

            <div>
                <div class="window_main" id="general-settings">
                </div>
            </div>
            <script type="text/javascript" src="js/pages/main/settings.js"></script>
        </div>
        <div class="abs window_bottom">
            Settings
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
