<div id="window_users" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
          <span class="float_left">
            Users
          </span>
            <span class="float_right">
                <a href="#" class="window_min"></a>
                <a href="#" class="window_resize"></a>
                <a href="#icon_dock_drive" class="window_close"></a>
            </span>
        </div>
        <div class="abs window_content" id="users_content">
            <div class="window_main user-tabs" id="friends_tabs">
                <ul>
                    <li><a class="users-tab-link" href="#friend_list">Friend List</a></li>
                    <li><a class="users-tab-link" href="#friends_requets">Requests</a></li>
                </ul>
                <div id="friend_list">
                    <script type="text/javascript" src="js/pages/main/friends.js"></script>
                </div>
                <div id="friends_requets">
                    <script type="text/javascript" src="js/pages/main/users.js"></script>
                </div>
            </div>
        </div>
        <div class="abs window_bottom">
            Friends
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
