memory_limit = 512M
upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 300
date.timezone = Europe/Vilnius
display_errors = Off
display_startup_errors = Off

log_errors = On
error_log = /proc/self/fd/2

error_reporting = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED
