<script type="text/javascript">
</script>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('messages', array('action' => 'addmessageform')));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('text'));
echo "<button value='";
echo $this->translator["save"];
echo "name='save' id='save_general_settings'>";
echo $this->translator["Save"];
echo "</button>";
echo $this->form()->closeTag();