<div class="c-window__scrollable-space">
    <?php if ($data): ?>
        <?php foreach ($data as $friend): ?>
            <?php $fullName = $friend['first_name'] . " " . $friend['second_name']; ?>

            <div class="c-chat-card">
                <div class="c-chat-card__inner">
                    <div class="c-chat-card__image-wrap">
                        <img src="<?php echo $friend['avatar']; ?>" alt="<?php echo $fullName; ?>"
                             class="c-chat-card__image">
                    </div>

                    <div class="c-chat-card__main">
                        <div class="c-chat-card__title">
                            <?php echo $fullName; ?>
                        </div>

                        <div class="c-chat-card__job">
                            <?php echo $friend['job']; ?>
                        </div>
                    </div>

                    <div class="c-chat-card__controls">
                        <button class="c-chat-card__enter-button js-open-chat" type="button"
                                with_user="<?php echo $friend['user_id']; ?>" user_name="<?php echo $fullName ;?>">
                            <svg class="icon-nw icon-nw-open-in-new-black-24" viewBox="0 0 24 24">
                                <path d="M0 0h24v24H0V0z" fill="none"/>
                                <path
                                    d="M19 19H5V5h7V3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z"/>
                            </svg>

                            Open
                        </button>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<script type="text/javascript">


    $(function () {
        $('.js-open-chat').on('click', function () {
            send_message_from_user_chat(this);
        });
    });

    function send_message_from_user_chat(element) {
        var to_user = $(element).attr('with_user');
        var user_name = $(element).attr('user_name');
        $('.message_to_user_area_chat').val("");
        $("#chat_user").remove();
        var chat_html = '' +
            '<div class="abs window" id="chat_user"><div class="abs window_inner"><div class="window_top"><span class="float_left">Chat with :'+user_name+'</span><span class="float_right"><a href="#" class="window_min"></a><a href="#" class="window_resize"></a><a href="#icon_dock_drive" class="window_close"></a></span></div><div class="abs window_content">' +
            '<div class="message_to_user_from_chat_list" style="display:hide;" title="Enter message" with_user=' + to_user + '>' +
            // '<p class="close_chat" with_user=' + to_user + '>X</p>' +
            '<div class="message_box" with_user=' + to_user + '>' + '</div>' +
            '<div class="user_chat" with_user=' + to_user + '>' +
            '<textarea class="message_to_user_area_chat" class="selectable-all" maxlength="2000" with_user=' + to_user + '></textarea>' +
            '<button class="submit" class="chanel_button" with_user=' + to_user + '>Send</button>' +
            '</div>' +
            '</div>'+ '</div> <div class="abs window_bottom">Chat</div> </div> <span class="abs ui-resizable-handle ui-resizable-se"></span> </div>';


        $("#chat_user").remove();

        $('body').append(chat_html);
        $(".message_to_user_from_chat_list").find('button').addClass("message_to_user_from_user_chats_button");
        $(".message_to_user_from_user_chats_button").bind("click", function () {
            send_chat(this);
        });
        $("#chat_user").show();
        get_old_messages(to_user);
        sync_chat();
    }

    function get_old_messages(to_user) {

        $.ajax({
            type: "POST",
            url: "sync/getoldmessages",
            dataType: "json",
            data: {"with_user": to_user}
        })
            .done(function (data) {
                console.info(data);
                $.each(data, function (index, message) {
                    if (message.current_user == message.from_user) {
                        $(".message_box[with_user=" + message.to_user + "]").append("<p class='allowSelectOneClick' message_id='" + message.message_id + "'>" + message.first_name + " " + message.second_name + ":" + message.text + "</p>");
                    } else {
                        $(".message_box[with_user=" + message.from_user + "]").append("<p class='allowSelectOneClick' message_id='" + message.message_id + "'>" + message.first_name + " " + message.second_name + ":" + message.text + "</p>");
                    }

                    $(".message_box[with_user=" + message.to_user + "]").animate({scrollTop: 10000}, 50);

                });


            });
    }

    function sync_chat(to_user) {

        $.ajax({
            type: "POST",
            url: "sync/sync",
            dataType: "json",
            data: {}
        })
            .done(function (data) {
                $.each(data.simple_messages, function (index, message) {
                    console.info($("p[message_id=" + message.message_id + "]").text());
                    if ($("p[message_id=" + message.message_id + "]").text().length == 0) {
                        if (message.current_user == message.from_user) {

                            $(".message_box[with_user=" + message.to_user + "]").append("<p class='allowSelectOneClick' message_id='" + message.message_id + "'>" + message.first_name + " " + message.second_name + ":" + message.text + "</p>");
                        } else {
                            $(".message_box[with_user=" + message.from_user + "]").append("<p class='allowSelectOneClick' message_id='" + message.message_id + "'>" + message.first_name + " " + message.second_name + ":" + message.text + "</p>");
                        }
                    }
                    $(".message_box[with_user=" + message.to_user + "]").animate({scrollTop: 10000}, 50);


                });
                $( "p.allowSelectOneClick" ).click(function( event ) {
                    event.stopPropagation();

                });
                $( "p.allowSelectOneClick" ).mousedown(function( event ) {
                    event.stopPropagation();

                });
                $( "p.allowSelectOneClick" ).mouseup(function( event ) {
                    event.stopPropagation();

                });
                setTimeout(sync_chat, 2000);
            });

    }

    function send_chat(element) {
        var to_user = $(element).attr('with_user');
        var text = $('.message_to_user_area_chat[with_user=' + to_user + ']').val();
        $('.message_to_user_area_chat[with_user=' + to_user + ']').val("");
        $(".message_box[with_user=" + to_user + "]").append("you:" + text + "<br/>");
        $('.message_to_user_from_user_chats_button[with_user=' + to_user + ']').val("");
        $(".message_box[with_user=" + to_user + "]").animate({scrollTop: 10000}, 50);
        $.ajax({
            type: "POST",
            url: "messages/addmessage",
            data: {text: text, to_user: to_user}
        });
    }
</script>

