<?php
$title = 'Please Login';
$this->headTitle($title);
?>
<?php if($this->message) {
    ?>
    <div class="alert alert-success" role="alert">
        <?php echo $this->message;?>
    </div>
    <?php
}?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="row">
    <div class="col-12">
<form action="/user/login" method="POST" id="auth_form" secret_auth_code="A7ZZ!-87kf&zz4ub">
<input type="text" placeholder="Email" name="email"/>
<br/>
<input type="password" placeholder="Password" name="password"/>
<br/>
<input type="submit" value="Login" />
</form>

</form>
    </div>
</div>
<div class="row">
<a href="/user/register">Register</a>
<br>
<a href="/user/restore">Restore</a>
</div>
