<?php
$title = 'Please Register';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

if ($this->message) {
    ?>
<div class="alert alert-success" role="alert">
        <?php echo $this->message;?>
    </div>
<?php
}
?>
<div class="row">
	<div class="col-6">
<form action="/user/register" method="post" id="register_form">
			<input type="text" placeholder="Login" name="login" /> <br /> <input
				type="text" placeholder="Email" name="email" /> <br /> <input
				type="password" placeholder="Password" name="password" /> <br /> <input
				type="password" placeholder="Repeat Password"
				name="confirm_password" /> <br /> <input type="submit"
				value="Register" />
		</form>
	</div>
	<div class="col-6">
  For security reason we dont send any emails, demo version also unable to restore account,
  please save your password in safe place.
	</div>
</div>
