<?php
$title = 'Please Register';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if($this->message) {
    ?>
    <div class="alert alert-success" role="alert">
        <?php echo $this->message;?>
    </div>
    <?php
}?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'register')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('login'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('confirm_password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
