<?php
$title = 'Please fill equal passwords';
$this->headTitle($title);
?>
<?php if($this->message) {
    ?>
    <div class="alert alert-success" role="alert">
       <?php echo $this->message;?>
    </div>
    <?php
}?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'reset')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('confirm_password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
