<?php
$title = 'Please fill email ';
$this->headTitle($title);
?>
<?php if($this->message) {
    ?>
    <div class="alert alert-success" role="alert">
       <?php echo $this->message;?>
    </div>
    <?php
}?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="row">
        <div class="col-12">
        <h1>Page dosent work on demo website</h1>
<form action="/user/restore" method="POST" id="restore_form">
<input type="text" name="email" placeholder="Email"/>
<br/>
<input type="submit" value="Restore"/>
</form>


        </div></div>
