<?php
$title = 'Please fill email ';
$this->headTitle($title);
?>
<?php if($this->message) {
    ?>
    <div class="alert alert-success" role="alert">
       <?php echo $this->message;?>
    </div>
    <?php
}?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="row">
        <div class="col-12">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'restore')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('email'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
        </div></div>
