<?php if( isset($settings[0]['avatar'])) {?>
<img src="<?php echo $settings[0]['avatar'] ?>" >
<?php }?>
<h1><?php echo $settings[0]['first_name'] ?></h1>
<h1><?php echo $settings[0]['second_name'] ?></h1>
<h1><?php echo $settings[0]['job'] ?></h1>
<h1><?php echo $settings[0]['country'] ?></h1>
<h1><?php echo $settings[0]['city'] ?></h1>
<h1><?php echo $settings[0]['about'] ?></h1>
<h1><?php echo $settings[0]['skype'] ?></h1>
<h1><?php echo $settings[0]['phone'] ?></h1>
<h1><?php echo $settings[0]['site'] ?></h1>