<div>
<?php
if($friends)
foreach($friends as $friend){
    if(isset($friend['first_name']) or isset($friend['second_name'])) {
    echo "<div class='user_container_block' userId='".$friend["user_id"]."'>";
    echo "<div class='member_name' userId='".$friend['user_id']."'>";

    echo "<div userId='".$friend['user_id']."' class='user_container_task'>";
//    echo "<div class='avatar'>";
//    echo "<img src=".$friend['avatar'].">";
//    echo "</div>";
    echo $friend['first_name']." ".$friend['second_name'];
    echo '<input type="button" value="+" userId='.$friend["user_id"].' class="add_user_to_task action_btn">';
    echo "</div>";
    echo "</div>";
    echo "</div>";
    }


}
?>
</div>
<script type="text/javascript">
    $(".add_user_to_task").on("click", function(){
        var user_id = $(this).attr("userId");
        var member_name = $(".user_container_task[userId="+user_id+"]").text();
        var member_markup =  "<div userId="+user_id+">"+member_name+"</div";
        $("#task_members_list").append(member_markup);
        });
</script>
