<div>
<?php
if($friends)
foreach($friends as $friend){
    echo "<span userId='".$friend["user_id"]."' class='project_member_span'>";
    echo "<div class='task_member_avatar'>";
    echo "<img src='" . $friend['avatar'] . "'>";
    echo "</div>";
    echo "<div class='member_name' userId='".$friend['user_id']."'><div userId='".$friend['user_id']."' class='user_container_project'>".$friend['first_name']." ".$friend['second_name']."</div></div>";
    echo '<input type="button" value="+" userId='.$friend["user_id"].' class="add_user_to_project action_btn">';
    echo "</span>";
}
?>
</div>
<script type="text/javascript">
    $(".add_user_to_project").on("click", function(){
        var user_id = $(this).attr("userId");
        var member_name = $(".user_container_project[userId="+user_id+"]").text();
        var member_markup =  "<div userId="+user_id+">"+member_name+"</div";
        if($("#project_members div[userId="+user_id+"]").html()) {
            alert("user already added");

        }
        else {
            $("#project_members").append(member_markup);
        }
        });
</script>
