<div>
<?php
if($friends)
foreach($friends as $friend){
    echo "<div userId='".$friend["user_id"]."' class='project_member_span'>";
    if(isset($friend['first_name'])) {
        
        echo "<div class='member_name' userId='".$friend['user_id']."'><span userId='".$friend['user_id']."' class='user_container_project'>".$friend['first_name']." ".$friend['second_name']."</span></div>";
    }
   else {
       echo "<div class='member_name' userId='".$friend['user_id']."'><span userId='".$friend['user_id']."' class='user_container_project'>anonymous</span></div>";
       
   }
    echo '<div style="margin:0;" userId='.$friend["user_id"].' class="add_user_to_project action_btn">Add</div>';
    echo "</div>";
}
?>
</div>
<script type="text/javascript">
    $(".add_user_to_project").on("click", function(){
        var user_id = $(this).attr("userId");
        var member_name = $(".user_container_project[userId="+user_id+"]").text();
        var member_markup =  "<div userId="+user_id+">"+member_name+"</div";
        if($("#project_members div[userId="+user_id+"]").html()) {
            alert("user already added");

        }
        else {
            $("#project_members").append(member_markup);
        }
        });
</script>
