<?php if(isset($settings["avatar"])) {?>
<img src="<?php echo $settings["avatar"]; ?>">
<?php }?>
<?php
if(isset($settings["first_name"])) echo $settings["first_name"];
if(isset($settings["second_name"])) echo $settings["second_name"];
if(isset($settings["phone"])) echo $settings["phone"];
if(isset($settings["about"])) echo $settings["about"];
if(isset($settings["job"])) echo $settings["job"];
if(isset($settings["country"])) echo $settings["country"];
if(isset($settings["city"])) echo $settings["city"];

?>


