<?php if(isset($settings["avatar"])) {?>
<div class='avatar'>
<img src="<?php echo $settings["avatar"]; ?>">
</div>
<?php }?>
<div class="user_profile">
<?php
echo "<div>".$settings["first_name"]." ".$settings["second_name"]."</div>";
echo "<div>".$settings["phone"]." ".$settings["job"]."</div>";
echo "<div>".$settings["country"]." ".$settings["city"]."</div>";
echo "<div>".$settings["about"]."</div>";
?>
</div>

