<?php
$title = 'General user Settings';
$this->headTitle($title);
?>

		<div class="col">
        <h1 class="load-avatar">Load avatar</h1>
        <form id="avatar_form" class="form-horizontal"
        	action="settings/savesettings" method="post">
        	<input type="file" name="avatar" id="avatar">
        </form>
		</div>
		<?php if(is_array($this->user_settings))
echo "<img src='" . $this->user_settings["avatar"] . "'>";
?>

<script type="text/javascript">
$(function () {
	$('#avatar').bind('change',upload_avatar);
});
        function upload_avatar(e) {
            var files= e.target.files;
            var file=files[0];
            var data = new FormData();
            data.append('file',file);
            var url  = "settings/savesettings";
            var request = new XMLHttpRequest();
            var xmlupload=request.upload;
            request.open("POST", url, true);
            request.send(data);
    }
</script>
<?php

// $form = $this->form;
// $form->setAttribute('action', $this->url('settings', array('action' => 'savesettings')));
// $form->prepare();
// echo $this->form()->openTag($form);
// echo $this->formRow($form->get('first_name'));
// echo $this->formRow($form->get('second_name'));
// echo $this->formRow($form->get('about'));
// echo $this->formRow($form->get('job'));
// echo $this->formRow($form->get('country'));
// echo $this->formRow($form->get('city'));
// echo $this->formRow($form->get('phone'));
// echo "<button value='save' name='save' class='action_btn' id='save_general_settings'>save</button>";
// echo $this->form()->closeTag();
?>
<br />

		<div class="col">
			<form action="settings/savesettings" method="post" id="user_general_settings" >
				<input name="first_name" type="text" / placeholder="First Name" <?php if(is_array($this->user_settings) and isset($this->user_settings['first_name'])) echo "value=".$this->user_settings['first_name'];?> />
				<br />
				<input name="second_name" type="text" / placeholder="Second Name" <?php if(is_array($this->user_settings) and isset($this->user_settings['second_name'])) echo "value='".$this->user_settings['second_name']."'";?> />
				<br /> 
				<input name="about" type="text" / placeholder="About" <?php if(is_array($this->user_settings) and isset($this->user_settings['about'])) echo "value='".$this->user_settings['about']."'"?> />
				<br />
				<input name="job" type="text" / placeholder="Job" <?php if(is_array($this->user_settings) and isset($this->user_settings['job'])) echo "value='".$this->user_settings['job']."'"?> /> 
				<br /> 
				<input	name="country" type="text" / placeholder="Country" <?php if(is_array($this->user_settings) and isset($this->user_settings['country'])) echo "value='".$this->user_settings['country']."'";?> />
			    <br /> 
				<input name="city" type="text" / placeholder="City" <?php if(is_array($this->user_settings) and isset($this->user_settings['city'])) echo "value='".$this->user_settings['city']."'";?>/>
				<br />
				<input name="phone" type="text" / placeholder="Phone" <?php if(is_array($this->user_settings) and isset($this->user_settings['phone'])) echo "value='".$this->user_settings['phone']."'";?>  />
				<br /> 
				<input type="submit" value="Save" class='action_btn' id="save_general_settings" />
			</form>
		</div>

<script type="text/javascript">
    $(function () {
       $("#user_general_settings").addClass("form-horizontal")
    });
</script>
