<?php
session_start();
$user = $_SESSION['user'];
?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv=Content-Type content="text/html;charset=UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <meta name="description" content="Octopus Desctop"/>
    <title>Octopus Desctop</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/css/style.css"/>
    <script type="text/javascript" src="/css/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/jquery-ui1.12/external/jquery/jquery.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-03HREGPV42"></script>
    <script>
        typeof window.jQuery !== 'undefined' ? console.log(window.jQuery.fn.jquery) : 'jQuery not found!';
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-03HREGPV42');
    </script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <img class="logo" src="<?php echo $this->basePath('img/octopus_logo.png') ?>" alt="Octopus"/>
        <div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Main Page</a></li>
                <li class="active"><a href="/octopus">Octopus</a></li>
                <li class="active"><a href="/main">Demo</a></li>
                <?php if (is_null($user)) { ?>
                    <li class="active"><a href="/user/login">Login</a></li>
                    <li class="active"><a href="/user/register">Register</a></li>
                <?php } elseif (!is_null($user)) { ?>
                <li class="active"><a href="/user/logout">Logout</a></li>
                <?php } ?>
                <li class="active"><a href="/donate">Donate</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container website_body">
    <?php echo $this->content; ?>
</div>
</body>
</html>
