<?php
if(session_status() !== PHP_SESSION_ACTIVE) session_start();
if(isset($_SESSION['user']))$user = $_SESSION['user'];
?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>
    <meta http-equiv=Content-Type content="text/html;charset=UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="description" content="Octopus Desctop" />
    <title>Octopus Desctop</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/style.css" />
    <script type="text/javascript" src="/css/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/jquery-ui1.12/external/jquery/jquery.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-03HREGPV42"></script>
</head>

<body id="body_os">

    <header>
        <nav class="header-nav" role="navigation">

            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="menu_link" href="/user/login">Login</a></li>
                    <li><a class="menu_link" href="/user/register">Register</a></li>
                    <li><a class="menu_link" href="/user/logout">Logout</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="body-container">
        <div class="container website_body">
            <?php echo $this->content; ?>
        </div>
    </div>

</body>

</html>
