<?php
session_start();
$user = $_SESSION['user'];
?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>
    <meta http-equiv=Content-Type content="text/html;charset=UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="description" content="Octopus Desctop" />
    <title>Octopus Desctop</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/style.css" />
    <script type="text/javascript" src="/css/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/jquery-ui1.12/external/jquery/jquery.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-03HREGPV42"></script>
    <script>
    typeof window.jQuery !== 'undefined' ? console.log(window.jQuery.fn.jquery) : 'jQuery not found!';
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'G-03HREGPV42');
    console.log("HELOOOOO SOOOSS")


    $(function() {

        var link = window.location.href;

        console.log(link);

        var splitUrl = link.split('/');
        console.log(splitUrl);
        console.log(splitUrl.length);

        var url = "";

        if (splitUrl.length == 5) {
            url = splitUrl[3] + "/" + splitUrl[4];
            console.log(url);
        } else {
            url = splitUrl[3];
            console.log(url);
        }
        console.log(url);
        $(".menu_link[href='/" + url + "']").css('border-bottom', '3px solid white');

    })
    </script>
</head>

<body>

    <header>
        <nav class="header-nav" role="navigation">

            <div class="container">
                <img class="logo" src="<?php echo $this->basePath('img/octopus_logo_horizontal_white.png') ?>" alt="Octopus" />
                <ul class="nav navbar-nav">
                    <li><a class="menu_link" href="/">Main Page</a></li>
                    <li><a class="menu_link" href="/octopus">Octopus</a></li>
                    <li><a class="menu_link" href="/main">Demo</a></li>
                    <?php if (is_null($user)) { ?>
                    <li><a class="menu_link" href="/user/login">Login</a></li>
                    <li><a class="menu_link" href="/user/register">Register</a></li>
                    <?php } elseif (!is_null($user)) { ?>
                    <li><a class="menu_link" href="/user/logout">Logout</a></li>
                    <?php } ?>
                    <li><a class="menu_link" href="/donate">Donate</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="body-container">
        <div class="container website_body">
            <?php echo $this->content; ?>
        </div>
    </div>

</body>

</html>