<?php
$user = $_SESSION['user'];
$lang = $user['user']->lang;
?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv=Content-Type content="text/html;charset=UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <meta name="description" content="JavaScript desktop environment built with jQuery."/>
    <title>jQuery Desktop</title>
    <link rel="stylesheet" href="assets/css/reset.css"/>
    <link rel="preload" as="image" href="assets/images/misc/wallpaper.jpg">
    <link rel="stylesheet" href="jquery-ui/jquery-ui.css"/>
    <link rel="stylesheet" href="jquery-ui/jquery-ui.structure.css"/>
    <link rel="stylesheet" href="jquery-ui/jquery-ui.theme.css"/>
    <link rel="stylesheet" href="css/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="css/bootstrap/css/bootstrap-responsive.css"/>
    <link rel="stylesheet" href="js/html5sortable/basscss.css"/>
    <link rel="stylesheet" href="assets/css/desktop.css"/>
    <script type="text/javascript" src="jquery-ui1.12/external/jquery/jquery.js"></script>
    <script type="text/javascript" src="jquery-ui1.12/jquery-ui.js"></script>
    <script type="text/javascript" src="assets/js/jquery.desktop.js"></script>
    <script type="text/javascript" src="js/html5sortable/html.sortable.js"></script>
</head>
<body>
<div class="abs" id="wrapper">
<div class="abs" id="desktop">
    <a class="abs icon" style="left:180px;top:420px;" href="#icon_dock_drive">
        <img src="assets/images/icons/icon_32_drive.png"/>
        <?php echo $this->translate("Hard Drive", false, $lang); ?>
    </a>
      <a class="abs icon" style="left: 264px;top: 420px;" href="#icon_dock_money">
       <img src="assets/images/icons/3.png"/>
        <?php  echo $this->translate("Task Manager", false, $lang); ?>
     </a>
    <!--  <a class="abs icon" style="left:420px;top:360px;" href="#icon_dock_payment">-->
<!--         <img src="assets/images/icons/payment.png"/> -->
        <?php // echo $this->translate("Market", false, $lang); ?>
<!--     </a> -->
    <a class="abs icon" style="left:340px;top:420px;" href="#icon_dock_network">
        <img src="assets/images/icons/icon_32_network.png"/>
        <?php echo $this->translate("Network", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:420px;top:420px;" href="#icon_dock_settings">
        <img src="assets/images/icons/setting.png"/>
        <?php echo $this->translate("Settings", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:740px;top:420px;" href="#icon_dock_search">
        <img src="assets/images/icons/search.png"/>
        <?php echo $this->translate("Search", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:500px;top:420px;" href="#icon_dock_users">
        <img src="assets/images/icons/users.png"/>
        <?php echo $this->translate("Users", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:580px;top:420px;" href="#icon_dock_messages">
        <img src="assets/images/icons/messages.png"/>
        <?php echo $this->translate("Messages", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:660px;top:420px;" href="#icon_dock_blogs">
        <img src="assets/images/icons/blogs.png"/>
        <?php echo $this->translate("Notes", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:820px;top:420px;" href="#icon_dock_admins">
        <img src="assets/images/icons/admin-icon.png"/>
        <?php echo $this->translate("Admin", false, $lang); ?>
    </a>


</div>
<div class="abs" id="bar_top">
    <span class="float_right" id="clock"></span>

<!--    <div style="margin-right:10px" class="float_right">-->
<!--        <span class="lang" lang="en"><img style="border:1px solid black;"-->
<!--                                          src="assets/images/icons/british-flag.jpg"/></span>-->
<!--        <span class="lang" lang="ru"><img style="border:1px solid black;"-->
<!--                                          src="assets/images/icons/russia-flag.gif"/></span>-->
<!--        <script type="text/javascript" src="js/pages/main/lang.js"></script>-->
<!---->
<!--    </div>-->
    <span class="float_right" id="clock"></span>
    <ul>
        <li id="notifications_block">
            <a class="menu_trigger" href="#" >Notifications</a>
         <ul class="menu">

<!--                <li>-->
<!--                    <a href="http://jqueryenlightenment.com/">jQuery Enlightenment</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://jquery.com/">jQuery Home</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://jquerymobile.com/">jQuery Mobile</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://jqueryui.com/">jQuery UI</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://learningjquery.com/">Learning jQuery</a>-->
<!--                </li>-->
         </ul>
        </li>
        <script type="text/javascript">
            function sync_notifications(){

                $.ajax({
                    type: "POST",
                    url: "notifications/index",
                    dataType: "json",
                    data: {}
                })
                    .done(function(data) {
                        $( data ).each(function( index,value ) {
                            var notification_id =  value.id + "notification";
                            var notification_text = $("#"+notification_id).text();
                            if(notification_text.length == 0) {
                                var markup = "<li><a id='"+notification_id+"'>"+value.text+"</a></li>";
                                $("#notifications_block .menu").append(markup);

                            }
                        });
                        setTimeout(sync_notifications, 5000);
                    });

            }
            $(function (){sync_notifications();})


        </script>
        <li>
            <a class="menu_trigger" href="#">Manual</a>
<!--            <ul class="menu">-->
<!--                <li>-->
<!--                    <a href="http://diveintohtml5.info/">Dive Into HTML5</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://www.alistapart.com/articles/get-ready-for-html-5/">Get Ready for HTML5</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://html5boilerplate.com/">HTML5 Boilerplate</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://html5doctor.com/">HTML5 Doctor</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://html5.org/">HTML5 Intro</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://www.zeldman.com/superfriends/">HTML5 Super Friends</a>-->
<!--                </li>-->
<!--            </ul>-->
        </li>
        <li>
<!--            <a class="menu_trigger" href="#">Code</a>-->
<!--            <ul class="menu">-->
<!--                <li>-->
<!--                    <a href="assets/css/desktop.css">Desktop - CSS</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="assets/js/jquery.desktop.js">Desktop - JavaScript</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://github.com/nathansmith/jQuery-Desktop">GitHub Repository</a>-->
<!--                </li>-->
<!--            </ul>-->
        </li>
        <li>
            <a class="menu_trigger" href="#">Resets</a>
            <ul class="menu">
                <li>
                    <a id="reset_interface">Reset interface</a>
                    <script>
                        $(function(){
                            $("#reset_interface").on("click",function (){
                                window.location.reload();
                            });
                        });

                    </script>
                </li>
<!--                <li>-->
<!--                    <a href="http://adrian-rodriguez.net/">Wallpaper by Adrian Rodriguez</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="http://tango.freedesktop.org/Tango_Desktop_Project">Icons - Tango Desktop Project</a>-->
<!--                </li>-->
            </ul>
        </li>
    </ul>

</div>
<div class="abs" id="bar_bottom">
    <a class="float_left" href="#" id="show_desktop" title="Show Desktop">
        <img src="assets/images/icons/icon_22_desktop.png"/>
    </a>
    <ul id="dock">
        <li id="icon_dock_money">
            <a href="#window_money">
                <img src="assets/images/icons/3.png"/>
                Tasks
            </a>
        </li>
<!--         <li id="icon_dock_payment"> -->
<!--             <a href="#window_payment"> -->
<!--                 <img src="assets/images/icons/payment.png"/> -->
<!--                 Money -->
<!--             </a> -->
<!--         </li> -->
        <li id="icon_dock_drive">
            <a href="#window_drive">
                <img src="assets/images/icons/icon_22_drive.png"/>
                Hard Drive
            </a>
        </li>
        <li id="icon_dock_disc">
            <a href="#window_disc">
                <img src="assets/images/icons/icon_22_disc.png"/>
                Audio CD
            </a>
        </li>
        <li id="icon_dock_network">
            <a href="#window_network">
                <img src="assets/images/icons/icon_22_network.png"/>
                Network
            </a>
        </li>
        <li id="icon_dock_settings">
            <a href="#window_settings">
                Setting
            </a>
        </li>
        <li id="icon_dock_search">
            <a href="#window_search">
                <?php echo $this->translate("Search", "false", 'ru'); ?>
            </a>
        </li>
        <li id="icon_dock_users">
            <a href="#window_users">
                Users
            </a>
        </li>
        <li id="icon_dock_messages">
            <a href="#window_messages">
                Messages
            </a>
        </li>
        <li id="icon_dock_admins">
            <a href="#window_admins">
                Admin
            </a>
        </li>
        <li id="icon_dock_blogs">
            <a href="#window_blogs">
                Blogs
            </a>
        </li>
    </ul>
    <a class="float_right" href="http://www.firehost.com/?ref=spon_nsmith_desktop-sonspring" title="Secure Hosting">
        <img src="assets/images/misc/firehost.png"/>
    </a>
</div>
    <div id="window_drive" class="abs window">
        <div class="abs window_inner">
            <div class="window_top">
          <span class="float_left">
          <img class="parent_directory" dir_key='0' src="assets/images/gui/left.png"/>
            <img src="assets/images/icons/icon_16_drive.png"/>
            Hard Drive
          </span>
          <span class="float_right">
            <a href="#" class="window_min"></a>
            <a href="#" class="window_resize"></a>
            <a href="#icon_dock_drive" class="window_close"></a>
          </span>
            </div>
            <div class="abs window_content">
                <div class="window_main" id="hard_drive">

                </div>
                <script type="text/javascript" src="js/pages/main/files.js"></script>
            </div>
            <div class="abs window_bottom">
                Storage in use: 119.1 GB
            </div>
        </div>
        <span class="abs ui-resizable-handle ui-resizable-se"></span>
    </div>

    <div id="window_network" class="abs window">
        <div class="abs window_inner">
            <div class="window_top">
          <span class="float_left">
            <img src="assets/images/icons/icon_16_network.png"/>


          </span>
          <span class="float_right">
            <a href="#" class="window_min"></a>
            <a href="#" class="window_resize"></a>
            <a href="#icon_dock_network" class="window_close"></a>
          </span>
            </div>
            <div id="network_frame">

                <span id="go_to_network">Go To Network</span>
                <script type="text/javascript">
                    $("#go_to_network").bind("click", function () {
                        refresh_network();
                    });
                </script>
                <div class="abs" id="network">

                </div>
            </div>

            <script type="text/javascript" src="js/pages/main/network.js"></script>
        </div>
        <span class="abs ui-resizable-handle ui-resizable-se"></span>
    </div>
<div id="window_settings" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
          <span class="float_left">
            <img src="assets/images/icons/setting_22.png"/>
            Settings
          </span>
          <span class="float_right">
            <a href="#" class="window_min"></a>
            <a href="#" class="window_resize"></a>
            <a href="#icon_dock_setting" class="window_close"></a>
          </span>
        </div>
        <div class="abs window_content" id="settings_content">

            <div>
                <div class="window_main" id="general-settings">
                </div>
            </div>
            <script type="text/javascript" src="js/pages/main/settings.js"></script>
        </div>
        <div class="abs window_bottom">
            Settings
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
    <div id="window_money" class="abs  window">
        <div class="abs window_inner">
            <div class="window_top">
          <span class="float_left">
            <img src="assets/images/icons/3.png"/>
             Tasks
          </span>
          <span class="float_right">
            <a href="#" class="window_min"></a>
            <a href="#" class="window_resize"></a>
            <a href="#icon_dock_tasks" class="window_close"></a>
          </span>
        </div>
            <div  class="window_content abs" id="tasks_content">
                <div id="tasks_tabs" class="window_main">
                    <span id="go_to_projects">Go To Projects</span>
                    <script type="text/javascript">
                    $("#go_to_projects").bind("click", function () {
                    refresh_boards();
                    });
                    </script>
                <div id="tasks_transaction">
                     <script type="text/javascript" src="js/pages/main/tasks_window.js"></script>
                </div>

</div>
            </div>
            <div class="abs window_bottom">
               Task Manager
            </div>
        </div>
        <span class="abs ui-resizable-handle ui-resizable-se"></span>
    </div>
<div id="window_search" class="abs  window">
    <div class="abs window_inner">
        <div class="window_top">
          <span class="float_left">
            Search
          </span>
          <span class="float_right">
            <a href="#" class="window_min"></a>
            <a href="#" class="window_resize"></a>
            <a href="#icon_dock_search" class="window_close" id="close_search"></a>
          </span>
        </div>
        <div class="window_content abs" id="search_content">
            <div class="window_aside">
                Search
            </div>

            <div id="search_tabs" class="abs window_content">
                <div class="window_main user-tabs" >
                <ul>
                    <li><a class="users-tab-link" href="#google_search">Google Search</a></li>
                    <li><a class="users-tab-link" href="#user_search_div">User Search</a></li>
                </ul>
                </div>
                <div id="google_search">
                        <input type="text" id="google_search_input"/>
                        <button value="search" id="google_search_button">search</button>
                </div>
                <div id="user_search_div">
                    <script type="text/javascript" src="js/pages/main/search.js"></script>
                </div>
            </div>
        </div>
        <div class="abs window_bottom">
            Search
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>
<div id="window_users" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
          <span class="float_left">
            Users
          </span>
          <span class="float_right">
            <a href="#" class="window_min"></a>
            <a href="#" class="window_resize"></a>
            <a href="#icon_dock_users" class="window_close" id="close_users"></a>
          </span>
        </div>
        <div class="abs window_content" id="users_content">
            <div class="window_main user-tabs" id="friends_tabs">
                <ul>
                    <li><a class="users-tab-link" href="#friend_list">Friend List</a></li>
                    <li><a class="users-tab-link" href="#friends_requets">Requests</a></li>
                </ul>
                <div id="friend_list">
                    <script type="text/javascript" src="js/pages/main/friends.js"></script>
                </div>
                <div id="friends_requets">
                    <script type="text/javascript" src="js/pages/main/users.js"></script>
                </div>
            </div>
        </div>
        <div class="abs window_bottom">
            Friends
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>

<div id="window_messages" class="c-window r-border-box-area abs window">
    <div class="c-window__inner _abs window_inner">
        <div class="c-window__title-bar window_top">
            <div class="c-window__title float_left">
                Messages
            </div>

            <div class="c-window__window-controls float_right">
                <a class="c-window__window-control window_min" href="#">
                    <svg class="icon-nw icon-nw-window-rollup-16" viewBox="0 0 16 16">
                        <path d="M14.5 14h-13c-.4 0-.8-.3-.8-.8s.3-.8.8-.8h13c.4 0 .8.3.8.8s-.4.8-.8.8z"/>
                    </svg>
                </a>

                <a class="c-window__window-control window_resize" href="#">
                    <svg class="icon-nw icon-nw-window-maximize-16" viewBox="0 0 16 16">
                        <path d="M12 1H4C2.3 1 1 2.3 1 4v8c0 1.7 1.3 3 3 3h8c1.7 0 3-1.3 3-3V4c0-1.7-1.3-3-3-3zm1.5 11c0 .8-.7 1.5-1.5 1.5H4c-.8 0-1.5-.7-1.5-1.5V4c0-.8.7-1.5 1.5-1.5h8c.8 0 1.5.7 1.5 1.5v8z"/>
                    </svg>
                </a>

                <a class="c-window__window-control window_close" href="#icon_dock_messages" id="close_messages">
                    <svg class="icon-nw icon-nw-window-close-16" viewBox="0 0 16 16">
                        <path d="M14.5 13.5c.3.3.3.8 0 1.1-.2.1-.3.2-.5.2s-.4-.1-.5-.2L8 9.1l-5.5 5.5c-.2.1-.3.2-.5.2s-.4-.1-.5-.2c-.3-.3-.3-.8 0-1.1L6.9 8 1.5 2.5c-.3-.3-.3-.8 0-1.1.3-.3.8-.3 1.1 0L8 6.9l5.5-5.5c.3-.3.8-.3 1.1 0 .3.3.3.8 0 1.1L9.1 8l5.4 5.5z"/>
                    </svg>
                </a>
            </div>
        </div>

        <div class="abs window_content" id="messages_content">
            <div class="window_aside">
                Messages
            </div>

            <div class="abs window_content" id="messages_tabs">
                <div class="window_main user-tabs">
                <ul>
                    <li><a class="users-tab-link" href="#chats">Chats</a></li>
                    <li><a class="users-tab-link" href="#chanels">Chanels</a></li>
                    <li><a class="users-tab-link" href="#private_chanels">Private Chanels</a></li>
                    <li><a class="users-tab-link" href="#private_chanels_admin">Private Chanels Settings</a></li>
                    <li><a class="users-tab-link" href="#create_chanel">Create Chanel</a></li>
                </ul>

                </div>
                <div id="chats">
                    <script type="text/javascript" src="js/pages/main/messages.js"></script>
                </div>
                <div id="chanels">
                    <script type="text/javascript" src="js/pages/main/chanels.js"></script>
                </div>
                <div id="private_chanels">
                    <script type="text/javascript" src="js/pages/main/private_chanels.js"></script>
                </div>
                 <div id="create_chanel">
                    <div>
                     <input name="chanel_name" type="text" id="chanel_name">
                     <input name="is_private" type="checkbox" id="is_private"> is private
                     <button id="create_chanel_submit">create chanel</button>
                    </div>
                    <script type="text/javascript" src="js/pages/main/create_chanel.js"></script>
                </div>

                <div id="private_chanels_admin">
                    <script type="text/javascript" src="js/pages/main/private_chanels_admin.js"></script>
                </div>
            </div>
        </div>
        <div class="abs window_bottom">
            Messages
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>

<div id="window_admins" class="abs window">
    <div class="abs window_inner">
        <div class="window_top">
          <span class="float_left">
           Administration
          </span>
          <span class="float_right">
            <a href="#" class="window_min"></a>
            <a href="#" class="window_resize"></a>
            <a href="#icon_dock_drive" class="window_close"></a>
          </span>
        </div>
        <div class="abs window_content" id="admins_content">
            <div class="window_aside">
                Administration
            </div>

        </div>
        <div class="abs window_bottom">
            Administration
        </div>
    </div>
    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>

<div id="window_blogs" class="c-window r-border-box-area abs window">
    <div class="c-window__inner _abs window_inner">
        <div class="c-window__title-bar window_top">
            <div class="c-window__title float_left">
                Notes
            </div>

            <div class="c-window__window-controls float_right">
                <a class="c-window__window-control window_min" href="#">
                    <svg class="icon-nw icon-nw-window-rollup-16" viewBox="0 0 16 16">
                        <path d="M14.5 14h-13c-.4 0-.8-.3-.8-.8s.3-.8.8-.8h13c.4 0 .8.3.8.8s-.4.8-.8.8z"/>
                    </svg>
                </a>

                <a class="c-window__window-control window_resize" href="#">
                    <svg class="icon-nw icon-nw-window-maximize-16" viewBox="0 0 16 16">
                        <path d="M12 1H4C2.3 1 1 2.3 1 4v8c0 1.7 1.3 3 3 3h8c1.7 0 3-1.3 3-3V4c0-1.7-1.3-3-3-3zm1.5 11c0 .8-.7 1.5-1.5 1.5H4c-.8 0-1.5-.7-1.5-1.5V4c0-.8.7-1.5 1.5-1.5h8c.8 0 1.5.7 1.5 1.5v8z"/>
                    </svg>
                </a>

                <a class="c-window__window-control window_close" href="#icon_dock_blogs">
                    <svg class="icon-nw icon-nw-window-close-16" viewBox="0 0 16 16">
                        <path d="M14.5 13.5c.3.3.3.8 0 1.1-.2.1-.3.2-.5.2s-.4-.1-.5-.2L8 9.1l-5.5 5.5c-.2.1-.3.2-.5.2s-.4-.1-.5-.2c-.3-.3-.3-.8 0-1.1L6.9 8 1.5 2.5c-.3-.3-.3-.8 0-1.1.3-.3.8-.3 1.1 0L8 6.9l5.5-5.5c.3-.3.8-.3 1.1 0 .3.3.3.8 0 1.1L9.1 8l5.4 5.5z"/>
                    </svg>
                </a>
            </div>
        </div>

        <div class="c-window__main _abs _window_content" id="notes_content">
            <!--
            <div class="c-window__aside window_aside">
                Notes
            </div>
            -->

            <div class="c-window__tabs-wrap _abs _window_content" id="notes_tabs">
                <div class="c-window__tabs window_main user-tabs">
                    <ul class="c-window__tabs-inner">
                        <li class="c-window__tab"><a class="users-tab-link" href="#new_blog">Create Post</a></li>
                        <li class="c-window__tab"><a class="users-tab-link" href="#list_blogs">Blogs</a></li>
                    </ul>
                </div>

                <div class="c-window__tab-content" id="new_blog"></div>
                <div class="c-window__tab-content" id="list_blogs"></div>

                <script type="text/javascript" src="js/pages/main/blogs.js"></script>
            </div>
        </div>

        <div class="c-window__status-bar _abs _window_bottom">
            <div class="c-window__status-text">
                Some text
            </div>
        </div>
    </div>

    <span class="abs ui-resizable-handle ui-resizable-se"></span>
</div>

<!-- <div id="window_payment" class="abs window_payment window"> -->
<!--     <div class="abs window_inner"> -->
<!--         <div class="window_top"> -->
<!--           <span class="float_left"> -->
<!--             Payment -->
<!--           </span> -->
<!--           <span class="float_right"> -->
<!--             <a href="#icon_dock_payment" class="window_close"></a> -->
<!--           </span> -->
<!--         </div> -->
<!--         <div class="abs"> -->
<!--             <div id="accordion_payemnts"> -->

<!--                 <h3>Wallet</h3> -->

<!--                 <div id="wallet"> -->
<!--                     test -->
<!--                 </div> -->
<!--                 <script type="text/javascript" src="js/pages/main/wallet.js"></script> -->
<!--                 <h3>Market</h3> -->

<!--                 <div id="Market"> -->
<!--                     <div id="tag_cloud"> -->

<!--                     </div> -->
<!--                     <script type="text/javascript" src="js/pages/main/tags.js"></script> -->

<!--                 </div> -->
<!--             </div> -->

<!--         </div> -->
<!--     </div> -->
<!-- </div> -->
</body>
</html>