<?php
$user = $_SESSION['user'];
$this->translator = $GLOBALS["HELPERS"]["TRANSLATOR"];
?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
<meta http-equiv=Content-Type content="text/html;charset=UTF-8">
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<meta name="description" content="Octopus Desctop" />
<title>Octopus Desctop</title>
<link rel="stylesheet" href="assets/css/reset.css" />
<link rel="preload" as="image" href="assets/images/misc/wallpaper.jpg">
<link rel="stylesheet" href="jquery-ui/jquery-ui.css" />
<link rel="stylesheet" href="jquery-ui/jquery-ui.structure.css" />
<link rel="stylesheet" href="jquery-ui/jquery-ui.theme.css" />
<link rel="stylesheet" href="css/bootstrap/css/bootstrap.css" />
<link rel="stylesheet" href="css/bootstrap/css/bootstrap-responsive.css" />
<link rel="stylesheet" href="js/html5sortable/basscss.css" />
<link rel="stylesheet" href="assets/css/jquery-ui.css" />
<link rel="stylesheet" href="assets/css/desctop.css" />
<script type="text/javascript" src="/assets/js/jquery.js"></script>
<script type="text/javascript" src="jquery-ui-1.13.2/jquery-ui.js"></script>
<script type="text/javascript" src="assets/js/jquery.desktop.js"></script>
<script type="text/javascript" src="node_modules/ckeditor/ckeditor.js"></script>
</head>
<body>
	<div class="abs" id="wrapper">
		<!-- Desktop -->
        <?php include dirname(__FILE__)."/parts/desktop.phtml"; ?>
        <!-- Bars -->
        <?php include dirname(__FILE__)."/parts/bar-top.phtml"; ?>
        <?php include dirname(__FILE__)."/parts/bar-bottom.phtml"; ?>
        <!-- Window -->
        <?php include dirname(__FILE__)."/windows/drive.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/network.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/settings.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/money.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/search.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/users.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/messages.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/admins.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/blogs.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/frame.phtml"; ?>
        <?php // include dirname(__FILE__)."/windows/payment.phtml"; ?>

        <div id="window_frame_container" class="abs window" style="width:1200px;">
			<div class="abs window_inner">
				<div class="window_top">
					<span class="float_left"> <img
						src="assets/images/icons/iframe50.png" /> Frames
					</span> <span class="float_right"> <a href="#" class="window_min"></a>
						<a href="#" class="window_resize"></a> <a href="#icon_dock_drive"
						class="window_close"></a>
					</span>
				</div>
				<div class="frame_container_output"></div>
			</div>
			<span class="abs ui-resizable-handle ui-resizable-se"></span>
		</div>
	</div>
</body>
</html>
