<?php
$user = $_SESSION['user'];
?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv=Content-Type content="text/html;charset=UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <meta name="description" content="Octopus Desctop"/>
    <title>Octopus Desctop</title>
    <link rel="stylesheet" href="assets/css/reset.css"/>
    <link rel="preload" as="image" href="assets/images/misc/wallpaper.jpg">
    <link rel="stylesheet" href="jquery-ui/jquery-ui.css"/>
    <link rel="stylesheet" href="jquery-ui/jquery-ui.structure.css"/>
    <link rel="stylesheet" href="jquery-ui/jquery-ui.theme.css"/>
    <link rel="stylesheet" href="css/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="css/bootstrap/css/bootstrap-responsive.css"/>
    <link rel="stylesheet" href="js/html5sortable/basscss.css"/>
    <link rel="stylesheet" href="assets/css/desktop.css"/>
   <script type="text/javascript" src="/assets/js/jquery.js"></script>
<!--     <script type="text/javascript" src="/js/jquery3-6.js"></script>-->
    <script type="text/javascript" src="jquery-ui-1.13.2/jquery-ui.js"></script>
    <script type="text/javascript" src="assets/js/jquery.desktop.js"></script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=G-03HREGPV42"></script>
    <script>
        typeof window.jQuery !== 'undefined' ? console.log(window.jQuery.fn.jquery) : 'jQuery not found!';

        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-03HREGPV42');
    </script>
    <script type="text/javascript" src="node_modules/ckeditor/ckeditor.js"></script>
</head>
<body>
    <div class="abs" id="wrapper">
        <!-- Desktop -->
        <?php include dirname(__FILE__)."/parts/desktop.phtml"; ?>
        <!-- Bars -->
        <?php include dirname(__FILE__)."/parts/bar-top.phtml"; ?>
        <?php include dirname(__FILE__)."/parts/bar-bottom.phtml"; ?>
        <!-- Window -->
        <?php include dirname(__FILE__)."/windows/drive.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/network.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/settings.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/money.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/search.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/users.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/messages.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/admins.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/blogs.phtml"; ?>
        <?php include dirname(__FILE__)."/windows/frame.phtml"; ?>
        <?php // include dirname(__FILE__)."/windows/payment.phtml"; ?>
    </div>
<script type="text/javascript">
    (function($){
        $.fn.disableSelection = function() {
            return this
                .attr('unselectable', 'off')
                .css('user-select', 'all')
                .on('selectstart', true);
        };
    })(jQuery);
</script>
</body>
</html>
