<?php
// module/Settings/view/user/user/savesettings.phtml:

$title = 'Upload File';
$this->headTitle($title);
?>
	<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('files', array('action' => 'uploadfile')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('file'));
echo $this->formRow($form->get('file_title'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
