<div id="boards_div">
    <div class="col col-3">
        <ul class="connected">
            <?php
            foreach ($tasks as $task) {
                echo '<li>' . $task["task_name"] . $task["description"].'</li>';
            }
            ?>
        </ul>
    </div>
</div>
<script type="text/javascript">
    function bind_boards_events(){
        $('.connected').sortable({
            connectWith: '.connected'
        });
    }
    $(function() {
        bind_boards_events();
    });

</script>