<div>
<?php
if(isset($tasks)){
    foreach ($tasks as $task_key => $task_value){
        echo "<p class='arcihe_task_block' task_id='".$task_value[0]["id"]."'>".$task_value[0]["name"].
            "<span class='restore_task action_btn' task_id='".$task_value[0]["id"]."'> restore</span>&nbsp".
            "<span class='delete_task action_btn' task_id='".$task_value[0]["id"]."'> delete</span></p>";
    }
}
?>
</div>
<script type="text/javascript">
$(".restore_task").on("click",function (){
    var data = {"is_archive": "0", "id": $(this).attr("task_id"),"board_id":$("#boards_div > div").attr("board_id")};
    $.ajax({
        type: "POST",
        url: "tasks/updateTask",
        async: false,
        data: {data}
    }).done(function (data) {
        var project_id = $("#create_board_button").attr("project_id");
        $.ajax({
            type: "POST",
            url: "boards/index",
            async: false,
            data: {"project_id": project_id}
        })
            .done(function (data) {
                $("#tasks_transaction").html(data);
            });
    });
});

$(".delete_task").on("click",function (){
    var data = {"task_id": $(this).attr("task_id")};
    $.ajax({
        type: "POST",
        url: "tasks/deleteTask",
        async: false,
        data: {data}
    }).done(function (data) {
        var project_id = $("#create_board_button").attr("project_id");
        $.ajax({
            type: "POST",
            url: "boards/index",
            async: false,
            data: {"project_id": project_id}
        })
            .done(function (data) {
                $("#tasks_transaction").html(data);
            });
    });
});


</script>
