<div class="c-window__scrollable-space">

<div class="c-blog-post">
    <div class="c-blog-post__header">
        Create Post
    </div>

    <div class="c-blog-post__fields">
        <div class="c-blog-post__field">
            <input class="c-field" type="text" id="blog_title" placeholder="Post title">
        </div>

        <div class="c-blog-post__field">
            <textarea class="c-field is-post" id="new_blog_text" placeholder="Write your post"></textarea>
        </div>
    </div>


    <div class="c-blog-post__footer">
        <div class="c-blog-post__file">
            <label for="blog_attach_file" class="c-file">
                <input type="file" class="c-file__input" id="blog_attach_file" name="myfile" value="attach_file" accept=".png, .jpg, .jpeg">

                <span class="c-file__icon-wrap">
                    <svg class="icon-nw icon-nw-attach-file-16" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="m14.8 7.6-5.5 6.3c-2.1 2.4-5.6 2.8-7.7.7-2.1-2.1-2-5.8.1-8.2L7 .4c.3-.4.9-.4 1.3-.1.4.4.3 1 0 1.4L3 7.7c-1.5 1.7-1.5 4.1-.1 5.5 1.4 1.4 3.7 1.2 5.2-.5l5.5-6.3c.9-1 .9-2.6.1-3.4-.8-.8-2.3-.7-3.2.3L5.4 9c-.4.4-.4 1-.1 1.3.3.3.8.3 1.2-.1l4.8-5.5c.3-.4.9-.5 1.3-.1s.3 1 0 1.4l-4.8 5.5c-1 1.2-2.7 1.3-3.7.3s-1-2.8.1-4l5-5.7c1.6-1.8 4.1-2.1 5.7-.5 1.5 1.4 1.5 4.2-.1 6z"/>
                    </svg>
                </span>

                <span class="c-file__desc">
                    <span class="c-file__requirements">
                        *.png, *.jpg, *.jpeg
                    </span>

                    <span class="c-file__selection"></span>
                </span>
            </label>
        </div>

        <button class="c-button c-blog-post__save-button" type="button" value="save" id="blog_save" name="blog_image">
            <svg class="icon-nw icon-nw-add-fpost-24" viewBox="0 0 24 24">
                <path fill="none" d="M0 0h24v24H0z"/>
                <path d="M17 19.2H5V7h7V5H5c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2v-7h-2v7.2z"/>
                <path d="M19 2h-2v3h-3v2h3v3h2V7h3V5h-3V2zM7 9h8v2H7zM7 12v2h8v-2h-3zM7 15h8v2H7z"/>
            </svg>

            Add Post
        </button>
    </div>
</div>

    <!-- <p>only jpg and png</p> -->
    <!-- <input type="file" value="attach_file" id="blog_attach_file"> -->
</div>
<script type="text/javascript">
    $(function(){
       $("#blog_save").bind("click",function () {
            var text = $("#new_blog_text").val();
            var blog_title = $("#blog_title").val();
            var $file = document.getElementById("blog_attach_file");
            var files= $file.files;
            var file=files[0];
            var data = new FormData();
            data.append('file', file);
            data.append('text', text);
            data.append('blog_title', blog_title);
            var url  = "blog/saveblog";
            var request = new XMLHttpRequest();
            var xmlupload=request.upload;
            xmlupload.addEventListener('load', () => {
                alert("Post is created");

                $('#notes_tabs').tabs({
                    active: 0,
                });
            }, false);
            request.open("POST", url, true);
            request.send(data);
        });

        $('#blog_attach_file').on('change', function() {
            const [file] = this.files;

            if (file) {
                const $component = this.closest('.c-file');
                const $selection = $component.querySelector('.c-file__selection');

                $component.classList.add('has-value');
                $selection.innerText = file.name;
            }
        });
    });
</script>
