<?php 

foreach ($blogs as $blog) {
?>

<?php 
echo "<div><button class='delete_blog action_btn' blog_id='".$blog["blog_id"]."'>Delete</button>"."&nbsp<span class='c-post__title'>".$blog["blog_title"]."</span></div>";
?>
<?php 
}

?>
<script type="text/javascript">

$(function(){
$(".delete_blog").on("click",function(){

   var blog_id = $(this).attr("blog_id");
   $.post("blog/deleteBlog", {blog_id: blog_id}).done(function (data) {
	    $.ajax({
	        type: "POST",
	        url: "blog/getblogs"

	    })
	        .done(function( data ) {
	            $(".c-blog__posts").html(data);
	        });
	    $.ajax({
	        type: "POST",
	        url: "blog/deleteblogs"

	    })
	        .done(function( data ) {
	            $("#delete_blog").html(data);
	        });
       $('#notes_tabs').tabs({
           active: 0,
       });
   });

	
});
	
});

</script>