<div class="c-window__scrollable-space">
    <div class="c-blog">
        <?php if (!empty($blogs)): ?>
            <div class="c-blog__posts">
                <?php foreach ($blogs as $blog): ?>
                    <div class="c-post">
                        <div class="c-post__header">
                            <?php echo $blog['first_name']; ?>
                            <?php echo $blog['second_name']; ?>
                            <?php echo "<img src=".$blog['avatar'].">"; ?>
                            <?php echo $blog['job']; ?>
                            <?php echo $blog['date']; ?>
                        </div>

                        <div class="c-post__main">
                            <div class="c-post__image-wrap">
                                <img class="image" src="<?php echo $blog["file_name"]; ?>">
                            </div>
                            <?php echo $blog["blog_title"]; ?>
                            <div class="c-post__content">
                                <?php echo $blog["blog_content"]; ?>
                            </div>
                        </div>

                        <div class="c-post__footer">
                            <div class="c-post__comment-header">
                                Comments
                            </div>

                            <div class="c-leave-comment">
                                <div class="c-leave-comment__field">
                                    <textarea name="blog_comment" class="comment_blog_body c-field is-post" blog_id="<?php echo $blog["blog_id"]; ?>" placeholder="Comment..."></textarea>
                                </div>

                                <div class="c-leave-comment__footer">
                                    <button class="comment_blog c-button c-leave-comment__add-button"type="button" blog_id="<?php echo $blog["blog_id"]; ?>">
                                        Add comment
                                    </button>
                                </div>
                            </div>

                            <div class="c-post__post-comments">
                                <div class="blog_comments c-post__user-comments" blog_id="<?php echo $blog["blog_id"]; ?>"></div>

                                <div class="c-post__show-comments">
                                    <button class="show_comments c-button" blog_id="<?php echo $blog["blog_id"]; ?>">
                                        Show post comments
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <div class="c-blog__footer">
                <?php $offset += 5; ?>
                <button class="c-button blogs_more" type="button" value="get more" offset="<?php echo $offset; ?>">
                    Show more posts
                </button>
            </div>
        <?php else: ?>
            <div class="c-blog__no-posts">
                Not posts to show
            </div>
        <?php endif; ?>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $(".show_comments").on("click",function(){
            var blog_id = $(this).attr("blog_id");
            load_comments(blog_id);

        });

        function load_comments(blog_id){
            var comment_count = $('.blog_comments .c-comment').length;
            var data = {
                "blog_id": blog_id,
                "comment_count": comment_count,
            };

            $.ajax({
                type: "POST",
                url: "blog/getComments",
                data: data
            })
                .done(function (data) {
                    data = JSON.parse(data);
                    blog_id = false;

                    $(data).each(function( index ) {
                        const avatar = data[index].avatar;
                        const first_name = data[index].first_name;
                        const second_name = data[index].second_name;
                        const comment = data[index].comment;
                        const blog_id = data[index].blog_id;
                        const comment_string = `
                            <div class="c-comment">
                                <div class="c-comment__aside">
                                    <div class="c-comment__avatar">
                                        <img class="c-comment__avatar-image" src="${avatar}" alt="Avatar of ${first_name} ${second_name}">
                                    </div>
                                </div>

                                <div class="c-comment__main">
                                    <div class="c-comment__header">
                                        ${first_name} ${second_name}
                                    </div>

                                    <div class="c-comment__content">
                                        ${comment}
                                    </div>
                                </div>
                            </div>
                        `;

                        $(`.blog_comments[blog_id="${blog_id}"]`).append(comment_string);
                    });

                    if(data[0] != undefined) {
                        const $blogCommentsContainer = $(`.blog_comments[blog_id="${data[0].blog_id}"]`);
                        const $showMoreButton = `
                            <div class="c-post__show-more">
                                <button blog_id="${data[0].blog_id}" class="more_comments c-button">
                                    Show more
                                </button>
                            </div>
                        `;

                        // Remove existing 'Show More' button
                        $blogCommentsContainer.find(".c-post__show-more").remove();

                        $blogCommentsContainer.append($showMoreButton);

                        $(".more_comments").on("click",function (){
                            var blog_id = $(this).attr("blog_id");

                            // Remove existing 'Show More' button
                            $(this.closest(".c-post__show-more")).remove();

                            load_comments(blog_id);
                        });
                    }
                });
        }

        function clearTextField($element) {
            $element.val('');
        }

        $(".comment_blog").on("click",function(){
            const blog_id = $(this).attr("blog_id");
            const $commentField = $(`textarea[blog_id="${blog_id}"]`)
            const content_blog = $commentField.val();

            const data =  {
                "blog_id": blog_id,
                "comment": content_blog,
            };

            $.ajax({
                type: "POST",
                url: "blog/addCommentToBlog",
                data: data
            })
                .done(function (data) {
                    load_comments(blog_id);
                    clearTextField($commentField);
                });
        });

        $(".blogs_more").bind("click", function () {
            $.ajax({
                type: "POST",
                url: "blog/getblogs",
                data: {offset: $(this).attr("offset")}
            })
                .done(function (data) {
                    $("#list_blogs").append(data);
                });
        })
    });
</script>
