<div class="abs r-border-box-area" id="bar_bottom">
    <a class="bottom-bar-button show-desktop" href="#" id="show_desktop" title="Show Desktop">
        <img src="assets/images/icons/icon_22_desktop.png"/>
    </a>

    <ul id="dock">
        <li id="icon_dock_money">
            <a class="bottom-bar-button" href="#window_money">
                <img class="bottom-bar-button-image" src="assets/images/icons/3.png"/>
                Tasks
            </a>
        </li>
        <!--
        <li id="icon_dock_payment">
             <a class="bottom-bar-button" href="#window_payment">
                 <img class="bottom-bar-button-image" src="assets/images/icons/payment.png"/>
                 Money
             </a>
         </li>
        -->
        <li id="icon_dock_drive">
            <a class="bottom-bar-button" href="#window_drive">
                <img class="bottom-bar-button-image" src="assets/images/icons/icon_22_drive.png"/>
                Hard Drive
            </a>
        </li>
        <li id="icon_dock_disc">
            <a class="bottom-bar-button" href="#window_disc">
                <img class="bottom-bar-button-image" src="assets/images/icons/icon_22_disc.png"/>
                Audio CD
            </a>
        </li>
        <li id="icon_dock_network">
            <a class="bottom-bar-button" href="#window_network">
                <img class="bottom-bar-button-image" src="assets/images/icons/icon_22_network.png"/>
                Network
            </a>
        </li>
        <li id="icon_dock_settings">
            <a class="bottom-bar-button" href="#window_settings">
                Setting
            </a>
        </li>
        <li id="icon_dock_search">
            <a class="bottom-bar-button" href="#window_search">
                <?php echo $this->translate("Search", "false", 'ru'); ?>
            </a>
        </li>
        <li id="icon_dock_users">
            <a class="bottom-bar-button" href="#window_users">
                Users
            </a>
        </li>
        <li id="icon_dock_messages">
            <a class="bottom-bar-button" href="#window_messages">
                Messages
            </a>
        </li>
        <li id="icon_dock_admins">
            <a class="bottom-bar-button" href="#window_admins">
                Admin
            </a>
        </li>
        <li id="icon_dock_blogs">
            <a class="bottom-bar-button" href="#window_blogs">
                Blogs
            </a>
        </li>
    </ul>

    <a class="hosting" href="http://www.firehost.com/?ref=spon_nsmith_desktop-sonspring" title="Secure Hosting">
        <img src="assets/images/misc/firehost.png"/>
    </a>
</div>