<div class="abs r-border-box-area" id="bar_bottom">
    <a class="bottom-bar-button show-desktop" href="#" id="show_desktop" title="Show Desktop">
        <img src="assets/images/icons/icon_22_desktop.png"/>
    </a>

    <ul id="dock">
        <li id="icon_dock_money">
            <a class="bottom-bar-button" href="#window_money">
                <img class="bottom-bar-button-image" src="assets/images/icons/3.png"/>
                Tasks
            </a>
        </li>
        <li id="icon_dock_drive">
            <a class="bottom-bar-button" href="#window_drive">
                <img class="bottom-bar-button-image" src="assets/images/icons/icon_32_drive.png"/>
                Hard Drive
            </a>
        </li>
        <li id="icon_dock_network">
            <a class="bottom-bar-button" href="#window_network">
                <img class="bottom-bar-button-image" src="assets/images/icons/icon_32_network.png"/>
                Network
            </a>
        </li>
        <li id="icon_dock_settings">
            <a class="bottom-bar-button" href="#window_settings">
                <img class="bottom-bar-button-image" src="assets/images/icons/setting.png"/>
                Setting
            </a>
        </li>
        <li id="icon_dock_search">
            <a class="bottom-bar-button" href="#window_search">
                <img class="bottom-bar-button-image" src="assets/images/icons/search.png"/>
                <?php echo $this->translator["Search"]; ?>
            </a>
        </li>
        <li id="icon_dock_users">
            <a class="bottom-bar-button" href="#window_users">
                <img class="bottom-bar-button-image" src="assets/images/icons/users.png"/>
                Users
            </a>
        </li>
        <li id="icon_dock_messages">
            <a class="bottom-bar-button" href="#window_messages">
                <img class="bottom-bar-button-image" src="assets/images/icons/messages.png"/>
                Messages
            </a>
        </li>
      <li id="icon_dock_admins">
           <a class="bottom-bar-button" href="#window_admins">
              Email
           </a>
      </li>
        <li id="icon_dock_blogs">
            <a class="bottom-bar-button" href="#window_blogs">
                <img class="bottom-bar-button-image" src="assets/images/icons/blogs.png"/>
                Blogs
            </a>
        </li>
        <li id="icon_dock_frame">
            <a class="bottom-bar-button" href="#window_frame">
                Windows
            </a>
        </li>
    </ul>

    <a class="hosting" href="http://www.firehost.com/?ref=spon_nsmith_desktop-sonspring" title="Secure Hosting">
        <img style="width: 100px;height: 20px;"src="/img/octopus_logo.png"/>
    </a>
</div>
