<div class="abs" id="desktop">
    <a class="abs icon" style="left:180px;top:420px;" href="#icon_dock_drive">
        <img src="assets/images/icons/icon_32_drive.png"/>
        <?php echo $this->translate("Hard Drive", false, $lang); ?>
    </a>
    <a class="abs icon" style="left: 264px;top: 420px;" href="#icon_dock_money">
        <img src="assets/images/icons/3.png"/>
        <?php  echo $this->translate("Task Manager", false, $lang); ?>
     </a>
    <!--
    <a class="abs icon" style="left:420px;top:360px;" href="#icon_dock_payment">
        <img src="assets/images/icons/payment.png"/>
        <?php // echo $this->translate("Market", false, $lang); ?>
    </a>
    -->
    <a class="abs icon" style="left:340px;top:420px;" href="#icon_dock_network">
        <img src="assets/images/icons/icon_32_network.png"/>
        <?php echo $this->translate("Network", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:420px;top:420px;" href="#icon_dock_settings">
        <img src="assets/images/icons/setting.png"/>
        <?php echo $this->translate("Settings", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:740px;top:420px;" href="#icon_dock_search">
        <img src="assets/images/icons/search.png"/>
        <?php echo $this->translate("Search", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:500px;top:420px;" href="#icon_dock_users">
        <img src="assets/images/icons/users.png"/>
        <?php echo $this->translate("Users", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:580px;top:420px;" href="#icon_dock_messages">
        <img src="assets/images/icons/messages.png"/>
        <?php echo $this->translate("Messages", false, $lang); ?>
    </a>
    <a class="abs icon" style="left:660px;top:420px;" href="#icon_dock_blogs">
        <img src="assets/images/icons/blogs.png"/>
        <?php echo $this->translate("Blogs", false, $lang); ?>
    </a>
<!--    <a class="abs icon" style="left:820px;top:420px;" href="#icon_dock_admins">-->
<!--        <img src="assets/images/icons/admin-icon.png"/>-->
<!--        --><?php //echo $this->translate("Admin", false, $lang); ?>
<!--    </a>-->
 <!--     <a class="abs icon" style="left:1120px;top:100px;color: black" href="#icon_dock_frame"> -->
<!--         <img src="assets/images/icons/iframe50.png"/> -->
        <?php false; ?>
<!--     </a> -->

</div>
