<div class="abs" id="desktop">
	<a class="abs icon" style="left: 180px; top: 420px;"
		href="#icon_dock_drive"> <img
		src="assets/images/icons/icon_32_drive.png" />
        <?php echo  $this->translator["Hard_Drive"]; ?>
    </a> <a class="abs icon" style="left: 264px; top: 420px;"
		href="#icon_dock_money"> <img src="assets/images/icons/3.png" />
        <?php   echo $this->translator["Task_Manager"]; ?>
     </a> <a class="abs icon" style="left: 340px; top: 420px;"
		href="#icon_dock_network"> <img
		src="assets/images/icons/icon_32_network.png" />
           <?php   echo $this->translator["Network"]; ?>
    </a> <a class="abs icon" style="left: 420px; top: 420px;"
		href="#icon_dock_settings"> <img src="assets/images/icons/setting.png" />
              <?php   echo $this->translator["Settings"]; ?>
    </a> <a class="abs icon" style="left: 740px; top: 420px;"
		href="#icon_dock_search"> <img src="assets/images/icons/search.png" />
        <?php   echo $this->translator["Search"] ;?>
    </a> <a class="abs icon" style="left: 500px; top: 420px;"
		href="#icon_dock_users"> <img src="assets/images/icons/users.png" />
        <?php echo $this->translator["Users"]; ?>
    </a> <a class="abs icon" style="left: 580px; top: 420px;"
		href="#icon_dock_messages"> <img
		src="assets/images/icons/messages.png" />
        <?php   echo $this->translator["Messages"] ;?>
    </a> <a class="abs icon" style="left: 660px; top: 420px;"
		href="#icon_dock_blogs"> <img src="assets/images/icons/blogs.png" />
            <?php   echo $this->translator["Blogs"]; ?>
    </a> <a class="abs icon" style="left: 820px; top: 420px;"
		href="#icon_dock_admins"> <img
		src="assets/images/icons/admin-icon.png" />
		<?php echo $this->translator["Admin"]; ?>
    </a> <a class="abs icon"
		style="left: 1120px; top: 100px; color: black" href="#icon_dock_frame">
		<img src="assets/images/icons/iframe50.png" />
        <?php   echo $this->translator["Frames"]; ?>
     </a>
</div>
