<div class="col-12">If you want to support octopus, donate to :</div>
    <figure class="figure">
        <figcaption class="figure-caption">
         BTC : <b>37bw2qaPyTH9ctNivf6LKvJ634sZ6UyBvx</b>
        </figcaption>
        <figcaption class="figure-caption">
            USDT <b>ONLY ERC-20 TOKENS!</b>: <b>0x99Ac8B13F176e46594d5905bB4ccd85B7826BEE3</b>
        </figcaption>
        <figcaption class="figure-caption">
            ETC : <b>0x99b45f439af63b80eb06708d13de9e8e70da90ec</b>
        </figcaption>
        <figcaption class="figure-caption">
            BAT : <b>0xF0F3dbb7a88E868352d3cB142eDDB2f450fFa6cA</b>
        </figcaption>
        <figcaption class="figure-caption">
            ALGO : <b>SYKXNEXSC67ZFVBNSHB67G7O6SLJDDEAVZFAOZTVRO4FATXBECVRRYNZAU</b>
        </figcaption>
        <figcaption class="figure-caption">
            TRX : <b>TFkA9SWwzTLeJ1T46Us8coHZgcBEGwB463</b>
        </figcaption>
        <figcaption class="figure-caption">
            OKB : <b>0x53C442bFF25b24cd6c41fB3F96c36d8862108583</b>
        </figcaption>
    </figure>


    <div class="col-12"><a class="font-fifty" href='https://t.me/underwaterlight'>or telegramm @underwaterlight</a></div>


