<div class="container">
    <div class="col-12">

        <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
    </div>
    <div class="col-12">
        <?php echo sprintf($this->translate('Octopus is under active development. If you are interested in following the development of Octopus, This is a great resource for staying up to date with the latest developments!')); ?></p>

    </div>
</div>


<div class="container">

    <div class="col-12">
        <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
    </div>
    <div class="col-12">
        Our community is working on developing a community site to serve as a repository and
        gallery for Octopus modules. The project is available GitHub. The site is currently live and
        currently contains a list of some of the modules already available for Octopus.
        <a id="gut_hub_link" class="btn btn-success pull-right" href="https://github.com/banderas328/networks"
           target="_blank">Explore Octopus Modules</a>
    </div>

</div>

<div class="container">

    <div class="col-12">
        <h3 class="panel-title">Help &amp; Support</h3>
    </div>
    <div class="col-12">
        If you need any help or support while developing with Octopus, you may reach us via mail
        :
        <a href="mailto:anton.zhavrid.minsk@gmail.com?subject=From Octopus Website">anton.zhavrid.minsk@gmail.com</a>
        <a href='https://t.me/underwaterlight'>or telegramm @underwaterlight</a>
    </div>
</div>
<div class="container">
        <div class="col-12">
            <h3 class="panel-title"><?php echo $this->translate('Requirements') ?></h3>
        </div>
        <div class="col-12">
            Octopus can be installed on any cloud or internal server.
            Current Requirements:
            <ul>
                <li>Linux</li>
                <li>Apache 2.4</li>
                <li>PHP 7.4</li>
                <li>Maria DB 10.3</li>
                <li>Fresh Stable Desktop Google Chrome</li>
            </ul>
        </div>
        <img src="/img/demo/desctop.png" class="figure-img img-fluid rounded" alt="...">
    </div>
