<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Octopus is under active development. If you are interested in following the development of Octopus, This is a great resource for staying up to date with the latest developments!')); ?></p>

            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p>The community is working on developing a community site to serve as a repository and gallery for Octopus modules. The project is available GitHub. The site is currently live and currently contains a list of some of the modules already available for Octopus.</p>
                <p><a class="btn btn-success pull-right" href="https://github.com/banderas328/networks" target="_blank">Explore Octopus Modules</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Help &amp; Support</h3>
            </div>
            <div class="panel-body">
                <p>If you need any help or support while developing with Octopus, you may reach us via mail</p>
                <p><a href="mailto:anton.zhavrid.minsk@gmail.com?subject=From Octopus Website">Send Email</a></p>
            </div>
        </div>
    </div>
</div>
