    <figure class="figure">
        <img src="/img/demo/first_slider.png" class="figure-img img-fluid rounded" alt="...">
        <figcaption class="figure-caption">We develop a cloud operation system that allow businesses to
        get a single information center for their companies. A single center for remote and dedicated team
        </figcaption>
    </figure>
    <figure class="figure">
        <img src="/img/demo/second_slider.png"class="figure-img img-fluid rounded" alt="...">
        <figcaption class="figure-caption">Octopus can be installed on any cloud or internal server.</figcaption>
    </figure>


