<div class="container">
    <img src="/img/demo/first_slider.png" class="figure-img img-fluid rounded" alt="...">
    <div class="col-12">We develop a cloud operation system that allow businesses to
        get a single information center for their companies. A single center for remote and dedicated teams.
        It's all in one system. 100% free and open source. You can see with Demo link in header. If you have any
        feedback
        please send email to <a href="mailto:anton.zhavrid.minsk@gmail.com?subject=From Octopus Website">anton.zhavrid.minsk@gmail.com</a>
    </div>
</div>
<div class="container">
    <img src="/img/demo/second_slider.png" class="figure-img img-fluid rounded" alt="...">
    <div class="col-12">
        Octopus can be installed on any cloud or internal server.
        Current modlues:
        <ul>
            <li>Task manager</li>
            <li>Hard drive</li>
            <li>Network Connections</li>
            <li>Messages</li>
            <li>Blog</li>
            <li>Users</li>
            <li>Settings</li>
            <li>Search</li>
        </ul>
    </div>
</div>
<div class="container-flex">
    <img src="/img/demo/arctic-code-vault-contributor-default.png" class="figure-img img-fluid rounded mini-img"
         alt="arctic code vault contributor">
    <div class="col-12">Octopus selected for GitHub archive programm. On 02/02/2020 GitHub captured a snapshot of
        Octopus. And project archived to hardened film designed to last for 1,000 years, and stored in the GitHub Arctic
        Code Vault in a decommissioned coal mine deep beneath an Arctic mountain in Svalbard, Norway.
        <p class="lead"><a class="btn btn-success pull-right" href="https://archiveprogram.github.com/">Read More</a>
    </p>
    </div>
   </div>
<div class="container-flex">
    <img src="/img/demo/github.png" class="figure-img img-fluid rounded mini-img" alt="arctic code vault contributor">
    <div class="col-12">
        We will be glad to get development assist with octopus. If you want to develop octopus core please send your
        pull requests to Git Hub.
        <p class="lead"><a class="btn btn-success pull-right" href="https://github.com/banderas328"
                       target="_blank">Product owner</a></p>
    </div>
   
</div>
<div class="container">
    <div class="col-12">
        If you need any help or support while developing with Octopus, you may reach us via mail : <a
            href="mailto:anton.zhavrid.minsk@gmail.com?subject=From Octopus Website">Send Email</a></div>
</div>
<div class="container">
    <div class="col-12"><a href='https://t.me/underwaterlight'>or telegramm @underwaterlight</a></div>
</div>


